<?php

namespace Modules\Production\Services;

use Illuminate\Support\Facades\DB;use Modules\ProductDev\Models\CostSheet;use Modules\Production\Models\ProductionOrder;use RuntimeException;
class StandardCostSnapshotService
{
 public function attachIfAvailable(ProductionOrder$mo,string$source='CREATE'):ProductionOrder{return$this->attach($mo,$source,false,true);}
 public function requireForRelease(ProductionOrder$mo):ProductionOrder{return$this->attach($mo,'RELEASE',true,true);}
 public function forCosting(ProductionOrder$mo):ProductionOrder{return$this->attach($mo,'LEGACY',true,false);}
 public function verify(ProductionOrder$mo):void{if(!$mo->standard_cost_snapshot||!$mo->standard_cost_snapshot_hash)throw new RuntimeException("MO {$mo->doc_no} belum memiliki standard cost snapshot.");$hash=$this->hash($mo->standard_cost_snapshot);if(!hash_equals((string)$mo->standard_cost_snapshot_hash,$hash))throw new RuntimeException("Standard cost snapshot MO {$mo->doc_no} gagal verifikasi integritas.");}
 private function attach(ProductionOrder$mo,string$source,bool$required,bool$exact):ProductionOrder{return DB::transaction(function()use($mo,$source,$required,$exact){$locked=ProductionOrder::withoutGlobalScopes()->where('company_id',$mo->company_id)->whereKey($mo->id)->lockForUpdate()->firstOrFail();if($locked->standard_cost_snapshot_hash){$this->verify($locked);return$locked;}$q=CostSheet::withoutGlobalScopes()->where('company_id',$locked->company_id)->where('style_id',$locked->style_id)->where('status','APPROVED');if($exact)$q->where('bom_version_id',$locked->bom_version_id)->where('routing_version_id',$locked->routing_version_id);$sheet=$q->orderByDesc('version')->orderByDesc('id')->first();if(!$sheet&&$exact&&!$required)return$locked;if(!$sheet&&$exact&&$source==='RELEASE')throw new RuntimeException('MO release memerlukan cost sheet APPROVED untuk BOM dan routing snapshot yang sama.');if(!$sheet&&!$exact)$sheet=CostSheet::withoutGlobalScopes()->where('company_id',$locked->company_id)->where('style_id',$locked->style_id)->where('status','APPROVED')->orderByDesc('version')->orderByDesc('id')->first();if(!$sheet){if($required)throw new RuntimeException("MO {$locked->doc_no} belum memiliki cost sheet APPROVED.");return$locked;}$snapshot=$this->snapshot($sheet);$locked->update(['standard_cost_sheet_id'=>$sheet->id,'standard_cost_snapshot'=>$snapshot,'standard_cost_snapshot_hash'=>$this->hash($snapshot),'standard_cost_snapshotted_at'=>now(),'standard_cost_snapshot_source'=>$source]);return$locked->fresh();});}
 private function snapshot(CostSheet$s):array{$x=['cost_sheet_id'=>(int)$s->id,'doc_no'=>(string)$s->doc_no,'version'=>(int)$s->version,'bom_version_id'=>$s->bom_version_id?(int)$s->bom_version_id:null,'routing_version_id'=>$s->routing_version_id?(int)$s->routing_version_id:null,'fabric'=>(float)$s->fabric_cost,'trim'=>(float)$s->trim_cost,'labor'=>(float)$s->cm_cost,'overhead'=>(float)$s->overhead_cost,'subcon'=>(float)$s->subcon_cost,'other'=>(float)$s->other_cost,'fob'=>(float)$s->fob_price,'margin_pct'=>(float)$s->margin_pct];$x['manufacturing_total']=round($x['fabric']+$x['trim']+$x['labor']+$x['overhead']+$x['subcon']+$x['other'],4);return$x;}
 private function hash(array$snapshot):string{return hash('sha256',json_encode($this->canonical($snapshot),JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR));}
 private function canonical(array$snapshot):array{ksort($snapshot,SORT_STRING);foreach($snapshot as$k=>$v){if(is_array($v))$snapshot[$k]=$this->canonical($v);elseif(is_int($v)||is_float($v))$snapshot[$k]=(float)$v;}return$snapshot;}
}
