"use client";

import { useEffect,useState } from "react";
import { api } from "@/lib/api";
type Mo={id:number;doc_no:string};type Row={id:number;valuation_stage?:string;component:string;receipt_quantity?:string;provisional_value:string};
type Component={id:number;component:string;completeness_status:string;actual_cost:string;provisional_value:string;variance_amount:string;source_evidence:unknown};
type Costing={id:number;costing_version:number;fg_received_quantity:string;actual_total_cost:string;actual_cost_per_pcs:string;standard_cost_per_pcs:string;provisional_fg_value:string;component_variance_total:string;currency:string;status:string;source_hash:string;components:Component[];freeze:{status:string;freeze_version:number}|null};
type Valuation={policy:string;production_order:{id:number;doc_no:string;status:string};eligibility:any;wip:{totals:Array<{valuation_stage:string;component:string;quantity:string;value:string}>};fg:{events:Row[]};adjustments:any[];fail_closed_reason:string|null};
export default function Page(){const[mos,setMos]=useState<Mo[]>([]),[mo,setMo]=useState(""),[v,setV]=useState<Valuation|null>(null),[c,setC]=useState<Costing|null>(null),[error,setError]=useState<string|null>(null);
useEffect(()=>{api.get<{data:Mo[]}>("/production/orders?per_page=100").then(r=>setMos(r.data)).catch(()=>{});},[]);
async function load(id:string){setMo(id);setError(null);setV(null);setC(null);if(!id)return;try{const[a,b]=await Promise.all([api.get<Valuation>(`/finance/valuation/production-orders/${id}`),api.get<{costing:Costing|null}>(`/finance/costing/mo/${id}/fg-actual`)]);setV(a);setC(b.costing);}catch(e:unknown){setError(e instanceof Error?e.message:"Unable to load costing");}}
const money=(x:string|number)=>new Intl.NumberFormat("id-ID",{minimumFractionDigits:4,maximumFractionDigits:4}).format(Number(x));
return <div className="space-y-4"><div><h1 className="text-xl font-bold">WIP, FG & Actual Costing</h1><p className="text-sm text-slate-500">D-06/D-07 provisional valuation and D-09 frozen actual cost per PCS.</p></div>
<select className="rounded border px-3 py-2 text-sm" value={mo} onChange={e=>load(e.target.value)}><option value="">— select MO —</option>{mos.map(x=><option key={x.id} value={x.id}>{x.doc_no}</option>)}</select>{error&&<div className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</div>}
{v&&<><div className="grid gap-3 md:grid-cols-4"><Card label="MO" value={`${v.production_order.doc_no} · ${v.production_order.status}`}/><Card label="Eligibility" value={v.eligibility?.status??"NOT APPROVED"}/><Card label="FG Received Qty" value={c?.fg_received_quantity??"NOT CALCULATED"}/><Card label="Freeze" value={c?.freeze?.status??"PARTIAL / NOT FINAL"}/></div>
{(v.fail_closed_reason||(!c&&mo))&&<div className="rounded border border-amber-300 bg-amber-50 p-3 text-sm"><b>FAIL CLOSED:</b> {v.fail_closed_reason??"D09_COSTING_NOT_CALCULATED"}</div>}
{c&&<><div className="grid gap-3 md:grid-cols-4"><Card label="Actual Total" value={`${c.currency} ${money(c.actual_total_cost)}`}/><Card label="Actual / PCS" value={money(c.actual_cost_per_pcs)}/><Card label="Standard / PCS" value={money(c.standard_cost_per_pcs)}/><Card label="Costing Version" value={`v${c.costing_version} · ${c.status}`}/></div>
<section className="rounded border bg-white p-4"><h2 className="font-semibold">D-09 Component Breakdown</h2><table className="mt-2 w-full text-sm"><thead><tr className="text-left"><th>Component</th><th>Completeness</th><th className="text-right">Provisional</th><th className="text-right">Actual</th><th className="text-right">Variance</th></tr></thead><tbody>{c.components.map(r=><tr className="border-t" key={r.id}><td>{r.component}</td><td>{r.completeness_status}</td><td className="text-right">{money(r.provisional_value)}</td><td className="text-right">{money(r.actual_cost)}</td><td className="text-right">{money(r.variance_amount)}</td></tr>)}</tbody></table><p className="mt-2 break-all text-xs text-slate-500">Source hash: {c.source_hash}</p></section></>}
<section className="rounded border bg-white p-4"><h2 className="font-semibold">Provisional WIP</h2>{v.wip.totals.map((r,i)=><div className="grid grid-cols-4 border-t py-1 text-sm" key={i}><span>{r.valuation_stage}</span><span>{r.component}</span><span className="text-right">{r.quantity}</span><span className="text-right">{money(r.value)}</span></div>)}</section></>}
</div>}
function Card({label,value}:{label:string;value:string}){return <div className="rounded border bg-white p-3"><b>{label}</b><p className="text-sm">{value}</p></div>}
