<?php

use Illuminate\Support\Facades\DB;use Modules\Core\Models\User;use Modules\Cutting\Models\Lay;use Modules\Cutting\Models\LayRoll;use Modules\Cutting\Services\CuttingService;use Modules\Cutting\Services\LayExecutionService;use Modules\MasterData\Models\ShadeGroup;use Modules\Production\Services\MaterialIssueService;use Modules\Production\Services\OperationalIntegrityService;use Modules\Receiving\Models\FabricRoll;
function iteration15CutFixture():array{$fixture=shopFixture();[$user,$fabric,,$uom,,$warehouse,$mo,,,$colorway,$size]=$fixture;$roll=FabricRoll::where('roll_no','R001')->firstOrFail();app(MaterialIssueService::class)->issue($mo,$warehouse->id,[['material_id'=>$fabric->id,'qty'=>100,'uom_id'=>$uom->id,'roll_id'=>$roll->id]],$user);$cut=app(CuttingService::class)->create($mo->fresh(),[['colorway_id'=>$colorway->id,'size_id'=>$size->id,'qty_cut'=>100]],$user);return[$user,$fabric,$uom,$warehouse,$mo->fresh(),$roll->fresh(),$cut];}
function insertHistoricalMarker($cut,$roll,$uom):void{DB::table('marker_logs')->insert(['cut_order_id'=>$cut->id,'roll_id'=>$roll->id,'uom_id'=>$uom->id,'marker_length_m'=>2,'marker_length_use'=>2,'plies'=>20,'qty_fabric_used_m'=>40,'qty_fabric_used_use'=>40,'efficiency_pct'=>90,'created_at'=>now(),'updated_at'=>now()]);}
test('historical Marker blocks new Lay Roll without mutating history',function(){[$user,,$uom,,$mo,$roll,$cut]=iteration15CutFixture();insertHistoricalMarker($cut,$roll,$uom);$lay=app(LayExecutionService::class)->createLay($cut,20,$user);$before=(float)DB::table('fabric_dispatch_balances')->where('production_order_id',$mo->id)->where('roll_id',$roll->id)->value('qty_consumed');expect(fn()=>app(LayExecutionService::class)->addRoll($lay,$roll,10,$user))->toThrow(RuntimeException::class,'CUTTING_CONSUMPTION_CONFLICT')->and((float)DB::table('fabric_dispatch_balances')->where('production_order_id',$mo->id)->where('roll_id',$roll->id)->value('qty_consumed'))->toBe($before);});
test('Lay Roll blocks all new legacy Marker writes',function(){[$user,,,$warehouse,$mo,$roll,$cut]=iteration15CutFixture();$shade=ShadeGroup::create(['company_id'=>1,'code'=>'I15-'.uniqid(),'name'=>'Iteration 15']);$roll->update(['shade_group_id'=>$shade->id]);$lay=app(LayExecutionService::class)->createLay($cut,20,$user);app(LayExecutionService::class)->addRoll($lay,$roll->fresh(),40,$user);expect(fn()=>app(CuttingService::class)->recordMarker($cut,[['roll_id'=>$roll->id,'marker_length_m'=>1,'plies'=>10,'qty_fabric_used_m'=>10]],$user))->toThrow(RuntimeException::class,'BR-031')->and(DB::table('marker_logs')->where('cut_order_id',$cut->id)->count())->toBe(0);});
test('historical mixed evidence remains readable and mutation blocked',function(){[$user,,$uom,,$mo,$roll,$cut]=iteration15CutFixture();insertHistoricalMarker($cut,$roll,$uom);$lay=Lay::create(['company_id'=>1,'cut_order_id'=>$cut->id,'lay_no'=>$cut->doc_no.'-LEGACY','layer_count'=>10,'lay_date'=>now()->toDateString(),'shade_validation_enabled'=>false,'status'=>'IN_PROGRESS','created_by'=>$user->id]);LayRoll::create(['company_id'=>1,'lay_id'=>$lay->id,'fabric_roll_id'=>$roll->id,'uom_id'=>$uom->id,'qty_used'=>10,'shade_override'=>false,'created_by'=>$user->id]);app(CuttingService::class)->generateBundles($cut,$cut->lines->first()->id,20,$user);$result=app(OperationalIntegrityService::class)->inspect($mo,$user);expect($result['authority_conflict']['status'])->toBe('HISTORICAL_CONFLICT')->and($result['authority_conflict']['historical_mutation'])->toBeFalse()->and(fn()=>app(CuttingService::class)->complete($cut,$user))->toThrow(RuntimeException::class,'BR-031/067');});
test('operational matrix reports D-01 D-03 D-04 locked and ITS preserved',function(){[$user,,,, $mo]=iteration15CutFixture();$mo->update(['qty_produced'=>100]);$result=app(OperationalIntegrityService::class)->inspect($mo,$user);$matrix=app(OperationalIntegrityService::class)->authorityMatrix(1,$user);expect($result['qty_produced']['classification'])->toContain('NOT AUTHORITATIVE')->and($result['backflush']['uses_qty_produced'])->toBeFalse()->and($result['backflush']['bypasses_its'])->toBeFalse()->and($result['backflush']['convergence'])->toContain('BR-066')->and($matrix['states']['MARKER_LAY_CONSUMPTION_AUTHORITY'])->toBe('LAY_ROLL')->and($matrix['states']['PRODUCTION_OUTPUT_AUTHORITY'])->toBe('SEPARATE_NAMED_MEASURES')->and($matrix['states']['INVENTORY_AUTHORITY'])->toBe('ITS');});
test('operational integrity inspection is read-only',function(){[$user,,,, $mo]=iteration15CutFixture();$before=DB::table('stock_movements')->count();$result=app(OperationalIntegrityService::class)->inspect($mo,$user);expect($result['inventory']['authority'])->toBe('ITS')->and(DB::table('stock_movements')->count())->toBe($before)->and($result['writes_performed'])->toBeFalse();});
test('operational integrity enforces company isolation',function(){[,,,, $mo]=iteration15CutFixture();$company=DB::table('companies')->insertGetId(['code'=>'I15-'.uniqid(),'name'=>'Other','base_currency'=>'IDR','is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);$other=User::factory()->create(['company_id'=>$company]);expect(fn()=>app(OperationalIntegrityService::class)->inspect($mo,$other))->toThrow(RuntimeException::class,'akses');});
