<?php

use Laravel\Sanctum\Sanctum;use Modules\Cutting\Services\CuttingService;use Modules\ShopFloor\Exceptions\ScanConflictException;use Modules\ShopFloor\Models\ProductionScan;use Modules\ShopFloor\Services\DeviceService;use Modules\ShopFloor\Services\ScanService;
function stage10bFixture():array{[$user,,,,,,$mo,$op1,,$colorway,$size]=shopFixture();$cutting=app(CuttingService::class);$cut=$cutting->create($mo,[['colorway_id'=>$colorway->id,'size_id'=>$size->id,'qty_cut'=>10]],$user);$bundle=$cutting->generateBundles($cut,$cut->lines->first()->id,10,$user)[0];$enrolled=app(DeviceService::class)->enroll(1,['name'=>'Tablet Cutting','platform'=>'android'],$user);return[$user,$mo,$op1,$bundle,$enrolled['device'],$enrolled];}
it('menerbitkan token device terpisah dan revocation menghapus token',function(){[$user,,,,$device,$result]=stage10bFixture();$token=$user->tokens()->where('id',$device->token_id)->firstOrFail();expect($result['token'])->not->toBeEmpty()->and($token->abilities)->toBe(['shopfloor:scan'])->and($token->expires_at)->not->toBeNull();app(DeviceService::class)->revoke(1,$device->id,$user);expect($device->fresh()->status)->toBe('REVOKED')->and($user->tokens()->where('id',$token->id)->exists())->toBeFalse();});
it('device token ditolak dari endpoint permission administrasi',function(){[$user]=stage10bFixture();Sanctum::actingAs($user,['shopfloor:scan']);$this->getJson('/api/shopfloor/wip/1',['X-Company-Id'=>'1'])->assertForbidden();});
it('offline event applied sekali lalu replay aman',function(){[$user,,$op,$bundle,$device]=stage10bFixture();$event=['client_event_id'=>'evt-001','expected_bundle_version'=>0,'client_scanned_at'=>now()->subMinute()->toIso8601String(),'bundle_no'=>$bundle->bundle_no,'operation_id'=>$op->id,'direction'=>'IN','stage'=>'SEWING'];$svc=app(ScanService::class);$first=$svc->syncScan(1,$event,$user,$device);$again=$svc->syncScan(1,$event,$user,$device);expect($first['status'])->toBe('applied')->and($again['status'])->toBe('replayed')->and($again['scan']->id)->toBe($first['scan']->id)->and(ProductionScan::where('bundle_id',$bundle->id)->count())->toBe(1)->and($bundle->fresh()->scan_version)->toBe(1);});
it('event id payload berbeda dan stale bundle version menjadi conflict',function(){[$user,,$op,$bundle,$device]=stage10bFixture();$base=['client_event_id'=>'evt-002','expected_bundle_version'=>0,'client_scanned_at'=>now()->subMinute()->toIso8601String(),'bundle_no'=>$bundle->bundle_no,'operation_id'=>$op->id,'direction'=>'IN','stage'=>'SEWING'];$svc=app(ScanService::class);$svc->syncScan(1,$base,$user,$device);expect(fn()=>$svc->syncScan(1,array_merge($base,['direction'=>'OUT']),$user,$device))->toThrow(ScanConflictException::class,'payload berbeda');expect(fn()=>$svc->syncScan(1,array_merge($base,['client_event_id'=>'evt-003']),$user,$device))->toThrow(ScanConflictException::class,'Versi bundle sudah berubah');});
it('offline IN dan OUT berurutan menaikkan version deterministik',function(){[$user,,$op,$bundle,$device]=stage10bFixture();$svc=app(ScanService::class);$at=now()->subMinutes(2);$svc->syncScan(1,['client_event_id'=>'evt-in','expected_bundle_version'=>0,'client_scanned_at'=>$at->toIso8601String(),'bundle_no'=>$bundle->bundle_no,'operation_id'=>$op->id,'direction'=>'IN','stage'=>'SEWING'],$user,$device);$out=$svc->syncScan(1,['client_event_id'=>'evt-out','expected_bundle_version'=>1,'client_scanned_at'=>$at->addSecond()->toIso8601String(),'bundle_no'=>$bundle->bundle_no,'operation_id'=>$op->id,'direction'=>'OUT','stage'=>'SEWING'],$user,$device);expect($out['status'])->toBe('applied')->and($out['scan']->bundle_version)->toBe(2)->and($bundle->fresh()->scan_version)->toBe(2);});
