"use client";
import{useEffect,useState}from"react";import{api}from"@/lib/api";import{Button,Input,PageHeader,Select}from"@/components/ui";
interface Device{id:number;name:string;platform?:string|null;status?:string|null}interface Mo{id:number;doc_no:string;status:string}interface Line{id:number;name:string;code?:string}interface LineOutput{id:number;output_date:string;qty:string|number;target_qty?:string|number|null;achievement_pct?:string|number|null;production_order?:{doc_no?:string};line?:{name?:string}}interface Finish{id:number;qty:string|number;completed_at:string;bundle?:{bundle_no?:string};source_scan?:{operation?:{name?:string}}}
function Json({data}:{data:unknown}){return <pre className="overflow-auto rounded bg-slate-50 p-3 text-xs">{JSON.stringify(data,null,2)}</pre>}
export default function ShopFloorMonitorPage(){const[devices,setDevices]=useState<Device[]>([]);const[deviceName,setDeviceName]=useState("");const[devicePlatform,setDevicePlatform]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[mos,setMos]=useState<Mo[]>([]);const[wipMo,setWipMo]=useState("");const[wip,setWip]=useState<unknown>(null);const[finishing,setFinishing]=useState<Finish[]>([]);const[lines,setLines]=useState<Line[]>([]);const[outLine,setOutLine]=useState("");const[outDate,setOutDate]=useState(new Date().toISOString().slice(0,10));const[outputs,setOutputs]=useState<LineOutput[]>([]);
 const loadDevices=()=>api.get<{data:Device[]}>("/shopfloor/devices").then(r=>setDevices(r.data)).catch(e=>setError(e.message));useEffect(()=>{loadDevices();api.get<{data:Mo[]}>("/production/orders?per_page=100").then(r=>setMos(r.data));api.get<{data:Line[]}>("/master/lines?per_page=100").then(r=>setLines(r.data));},[]);
 async function enroll(){if(!deviceName)return;setBusy(true);try{await api.post("/shopfloor/devices",{name:deviceName,platform:devicePlatform||undefined});setDeviceName("");setDevicePlatform("");loadDevices();}catch(e){setError(e instanceof Error?e.message:"Gagal mendaftarkan perangkat");}finally{setBusy(false)}}async function revoke(id:number){setBusy(true);try{await api.delete(`/shopfloor/devices/${id}`);loadDevices();}finally{setBusy(false)}}
 async function loadMo(){if(!wipMo)return;setBusy(true);setError(null);try{const[a,b]=await Promise.all([api.get<{data:unknown}>(`/shopfloor/wip/${wipMo}`),api.get<{data:Finish[]}>(`/shopfloor/finishing/outputs?production_order_id=${wipMo}`)]);setWip(a.data);setFinishing(b.data);}catch(e){setError(e instanceof Error?e.message:"Gagal memuat monitor MO");}finally{setBusy(false)}}async function loadOutput(){if(!outLine)return;setBusy(true);try{const r=await api.get<{data:LineOutput[]}>(`/shopfloor/line-outputs?line_id=${outLine}&date=${outDate}`);setOutputs(r.data);}catch(e){setError(e instanceof Error?e.message:"Gagal memuat line output");}finally{setBusy(false)}}
 return <div className="space-y-4"><PageHeader eyebrow="Manufacturing" title="Monitor Shop Floor" description="Perangkat, WIP, canonical Finishing Output, dan persisted final Sewing output per line/hari."/>{error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Perangkat Scan</h2><div className="mt-2 flex flex-wrap items-end gap-2"><label className="text-sm">Nama *<Input value={deviceName} onChange={e=>setDeviceName(e.target.value)} className="block w-56"/></label><label className="text-sm">Platform<Input value={devicePlatform} onChange={e=>setDevicePlatform(e.target.value)} className="block w-40"/></label><Button loading={busy} disabled={!deviceName} onClick={enroll}>Daftarkan</Button></div><table className="mt-3 w-full text-sm"><tbody>{devices.map(d=><tr key={d.id} className="border-t"><td className="py-2">{d.name}</td><td>{d.platform??"-"}</td><td>{d.status??"-"}</td><td className="text-right"><Button size="sm" variant="danger" onClick={()=>revoke(d.id)}>Cabut</Button></td></tr>)}</tbody></table></section>
 <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">WIP & Finishing Output per MO</h2><div className="mt-2 flex gap-2"><Select value={wipMo} onChange={e=>setWipMo(e.target.value)} className="w-80"><option value="">— pilih MO —</option>{mos.map(m=><option key={m.id} value={m.id}>{m.doc_no} · {m.status}</option>)}</Select><Button variant="secondary" loading={busy} onClick={loadMo}>Muat</Button></div>{wip!==null&&<div className="mt-3"><Json data={wip}/></div>}<div className="mt-3 overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Bundle</th><th>Qty</th><th>Source operation</th><th>Completed</th></tr></thead><tbody>{finishing.map(row=><tr key={row.id} className="border-b"><td className="py-2">{row.bundle?.bundle_no??"-"}</td><td>{row.qty}</td><td>{row.source_scan?.operation?.name??"-"}</td><td>{new Date(row.completed_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>
 <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Persisted Final Sewing Output per Line/Hari</h2><div className="mt-2 flex gap-2"><Select value={outLine} onChange={e=>setOutLine(e.target.value)} className="w-72"><option value="">— pilih line —</option>{lines.map(l=><option key={l.id} value={l.id}>{l.name??l.code}</option>)}</Select><Input type="date" value={outDate} onChange={e=>setOutDate(e.target.value)} className="w-44"/><Button variant="secondary" loading={busy} onClick={loadOutput}>Muat</Button></div><div className="mt-3 overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Date</th><th>MO</th><th>Line</th><th>Output</th><th>Target snapshot</th><th>Achievement</th></tr></thead><tbody>{outputs.map(row=><tr key={row.id} className="border-b"><td className="py-2">{String(row.output_date).slice(0,10)}</td><td>{row.production_order?.doc_no??"-"}</td><td>{row.line?.name??"-"}</td><td>{row.qty}</td><td>{row.target_qty??"-"}</td><td>{row.achievement_pct==null?"-":`${row.achievement_pct}%`}</td></tr>)}</tbody></table></div></section></div>}
