<?php

namespace Modules\Production\Http\Controllers;
use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Routing\Controller;use Illuminate\Validation\Rule;use Modules\Core\Support\CurrentCompany;use Modules\Production\Models\MaterialIssue;use Modules\Production\Models\ProductionOrder;use Modules\Production\Services\MaterialIssueService;use Modules\Receiving\Models\FabricRoll;use RuntimeException;
class MaterialIssueController extends Controller
{
 public function __construct(private MaterialIssueService $service){}
 public function store(Request$r,ProductionOrder$mo):JsonResponse{$c=CurrentCompany::id();$d=$r->validate(['warehouse_id'=>['required','integer',Rule::exists('warehouses','id')->where('company_id',$c)],'lines'=>'required|array|min:1','lines.*.material_id'=>['required','integer',Rule::exists('materials','id')->where('company_id',$c)],'lines.*.qty'=>'required|numeric|min:0.0001','lines.*.uom_id'=>['required','integer',Rule::exists('uoms','id')->where('company_id',$c)],'lines.*.roll_id'=>['nullable','integer',Rule::exists('fabric_rolls','id')->where('company_id',$c)],'lines.*.location_id'=>'nullable|integer|exists:locations,id','lines.*.lot_no'=>'nullable|string|max:64']);return$this->domain(fn()=>response()->json($this->service->issue($mo,(int)$d['warehouse_id'],$d['lines'],$r->user()),201));}
 public function backflush(Request$r,ProductionOrder$mo):JsonResponse{$c=CurrentCompany::id();$d=$r->validate(['warehouse_id'=>['required','integer',Rule::exists('warehouses','id')->where('company_id',$c)]]);return$this->domain(function()use($r,$mo,$d){$x=$this->service->backflush($mo,(int)$d['warehouse_id'],$r->user());return response()->json(['data'=>$x,'message'=>$x?'Backflush diposting.':'Tidak ada delta backflush.'],$x?201:200);});}
 public function returnLeftover(Request$r,ProductionOrder$mo,FabricRoll$roll):JsonResponse{$c=CurrentCompany::id();$d=$r->validate(['warehouse_id'=>['required','integer',Rule::exists('warehouses','id')->where('company_id',$c)],'qty'=>'nullable|numeric|gt:0','uom_id'=>['nullable','integer',Rule::exists('uoms','id')->where('company_id',$c)],'reason'=>'nullable|string|max:1000']);return$this->domain(fn()=>response()->json($this->service->returnLeftover($mo,$roll,(int)$d['warehouse_id'],$r->user(),isset($d['qty'])?(float)$d['qty']:null,isset($d['uom_id'])?(int)$d['uom_id']:null,$d['reason']??null),201));}
 public function index(Request$r,ProductionOrder$mo):JsonResponse{return response()->json(MaterialIssue::where('production_order_id',$mo->id)->with('lines.material','lines.roll')->orderByDesc('id')->get());}
 private function domain(callable$f):JsonResponse{try{return$f();}catch(RuntimeException$e){return response()->json(['message'=>$e->getMessage()],422);}}
}
