"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Button, Input, PageHeader, Select, StatusBadge } from "@/components/ui";

type SoLine = { id: number; qty: string; style?: { style_no: string }; colorway?: { color?: { code: string; name: string } }; size?: { code: string } };
type So = { id: number; doc_no: string; status: string; ex_factory_date: string | null; customer?: { name: string }; lines?: SoLine[] };
type DeltaRequirement = { id: number; gross_qty: string; gross_delta_qty: string | null; net_qty: string; net_delta_qty: string | null; material?: { code: string; name: string } };
type AmendmentLine = { id: number; old_qty: string; new_qty: string; qty_delta: string; sales_order_line?: SoLine };
type Amendment = { id: number; doc_no: string; reason: string; status: string; old_ex_factory_date: string | null; new_ex_factory_date: string | null; sales_order?: So; lines?: AmendmentLine[]; delta_mrp_run?: { run_no: number; requirements?: DeltaRequirement[] } };
const fmt = (v: string | number | null) => Number(v ?? 0).toLocaleString("id-ID", { maximumFractionDigits: 4 });

export default function AmendmentsPage() {
  const [sos, setSos] = useState<So[]>([]); const [amendments, setAmendments] = useState<Amendment[]>([]);
  const [soId, setSoId] = useState(""); const [selected, setSelected] = useState<So | null>(null);
  const [quantities, setQuantities] = useState<Record<string, string>>({}); const [date, setDate] = useState(""); const [reason, setReason] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);

  const load = useCallback(async () => { try { const [orders, history] = await Promise.all([api.get<{ data: So[] }>("/sales/orders?status=CONFIRMED&per_page=100"), api.get<{ data: Amendment[] }>("/sales/amendments?per_page=100")]); setSos(orders.data); setAmendments(history.data); } catch (e) { setError(e instanceof Error ? e.message : "Gagal memuat amendment."); } }, []);
  useEffect(() => { load(); }, [load]);

  async function choose(value: string) { setSoId(value); setSelected(null); if (!value) return; try { const so = await api.get<So>(`/sales/orders/${value}`); setSelected(so); setDate(so.ex_factory_date ?? ""); setQuantities(Object.fromEntries((so.lines ?? []).map((line) => [String(line.id), line.qty]))); } catch (e) { setError(e instanceof Error ? e.message : "Gagal memuat SO."); } }
  async function createDraft() { if (!selected || reason.trim().length < 3) return; const lines = (selected.lines ?? []).filter((line) => Number(quantities[String(line.id)]) !== Number(line.qty)).map((line) => ({ sales_order_line_id: line.id, new_qty: Number(quantities[String(line.id)]) })); setBusy(true); setError(null); setMessage(null); try { const amendment = await api.post<Amendment>(`/sales/orders/${selected.id}/amendments`, { reason, new_ex_factory_date: date || null, lines }); setMessage(`Draft amendment ${amendment.doc_no} dibuat. Review lalu terapkan untuk menghasilkan MRP delta.`); setReason(""); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Gagal membuat amendment."); } finally { setBusy(false); } }
  async function apply(amendment: Amendment) { setBusy(true); setError(null); setMessage(null); try { const result = await api.post<Amendment>(`/sales/amendments/${amendment.id}/apply`, {}); setMessage(`${result.doc_no} diterapkan. SO tetap CONFIRMED; baseline dan MRP delta tersimpan.`); await load(); if (selected) await choose(String(selected.id)); } catch (e) { setError(e instanceof Error ? e.message : "Gagal menerapkan amendment."); } finally { setBusy(false); } }

  return <div className="space-y-6">
    <PageHeader eyebrow="Sales" title="Order Amendment & MRP Delta" description="BR-022: perubahan qty/ex-factory sebelum cutting; apply menyimpan MRP before/after dan material delta." actions={<Link href="/sales/orders" className="text-sm font-medium text-blue-600 hover:underline">Kembali ke Sales Order</Link>} />
    {error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p className="rounded bg-green-50 p-3 text-sm text-green-700">{message}</p>}
    <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Buat draft amendment</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-sm"><span className="mb-1 block font-medium">SO CONFIRMED</span><Select className="w-full" value={soId} onChange={(e) => choose(e.target.value)}><option value="">- pilih SO -</option>{sos.map((so) => <option key={so.id} value={so.id}>{so.doc_no} · {so.customer?.name}</option>)}</Select></label><label className="text-sm"><span className="mb-1 block font-medium">Ex-factory baru</span><Input type="date" value={date} onChange={(e) => setDate(e.target.value)} disabled={!selected} /></label></div>
      {selected && <div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-slate-50 text-left"><th className="p-2">Matrix</th><th className="p-2 text-right">Qty saat ini</th><th className="p-2">Qty baru</th></tr></thead><tbody>{(selected.lines ?? []).map((line) => <tr key={line.id} className="border-b"><td className="p-2">{line.style?.style_no} · {line.colorway?.color?.code} · {line.size?.code}</td><td className="p-2 text-right">{fmt(line.qty)}</td><td className="p-2"><Input className="w-40" type="number" min="0.0001" step="0.0001" value={quantities[String(line.id)] ?? line.qty} onChange={(e) => setQuantities((x) => ({ ...x, [String(line.id)]: e.target.value }))} /></td></tr>)}</tbody></table></div>}
      <label className="mt-3 block text-sm"><span className="mb-1 block font-medium">Alasan</span><Input value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Alasan amendment wajib" disabled={!selected} /></label><Button className="mt-3" loading={busy} disabled={!selected || reason.trim().length < 3} onClick={createDraft}>Simpan Draft Amendment</Button>
    </section>
    <section className="rounded-xl border bg-white p-4"><h2 className="mb-3 font-semibold">Riwayat amendment</h2><div className="space-y-3">{amendments.map((a) => <article key={a.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><b>{a.doc_no}</b><p className="text-sm text-slate-600">SO {a.sales_order?.doc_no} · {a.reason}</p><p className="text-xs text-slate-500">Ex-factory: {a.old_ex_factory_date ?? "—"} → {a.new_ex_factory_date ?? "—"}</p></div><div className="flex items-center gap-2"><StatusBadge status={a.status} />{a.status === "DRAFT" && <Button size="sm" variant="success" loading={busy} onClick={() => apply(a)}>Terapkan & Run Delta</Button>}</div></div><div className="mt-2 text-sm">{(a.lines ?? []).map((line) => <p key={line.id}>{line.sales_order_line?.style?.style_no} · {line.sales_order_line?.colorway?.color?.code} · {line.sales_order_line?.size?.code}: {fmt(line.old_qty)} → {fmt(line.new_qty)} ({Number(line.qty_delta) >= 0 ? "+" : ""}{fmt(line.qty_delta)})</p>)}</div>{a.delta_mrp_run && <div className="mt-3 rounded bg-slate-50 p-2 text-xs"><b>MRP Delta Run #{a.delta_mrp_run.run_no}</b>{(a.delta_mrp_run.requirements ?? []).map((r) => <p key={r.id}>{r.material?.code} {r.material?.name}: gross Δ {Number(r.gross_delta_qty) >= 0 ? "+" : ""}{fmt(r.gross_delta_qty)} · net Δ {Number(r.net_delta_qty) >= 0 ? "+" : ""}{fmt(r.net_delta_qty)}</p>)}</div>}</article>)}{amendments.length === 0 && <p className="text-sm text-slate-500">Belum ada amendment.</p>}</div></section>
    <p className="text-xs text-slate-500">MRP delta adalah evidence kebutuhan material. PR/PO/MO tidak diubah otomatis karena aturan adjustment/cancellation masing-masing belum didefinisikan.</p>
  </div>;
}
