<?php

namespace Modules\Receiving\Services;
use Illuminate\Support\Facades\DB;use Modules\Core\Models\User;use Modules\Core\Services\NumberingService;use Modules\Inventory\Services\InventoryTransactionService;use Modules\Receiving\Models\FabricRoll;use Modules\Receiving\Models\GoodsReceipt;use Modules\Receiving\Models\GrLine;use Modules\Receiving\Models\InwardInspection;use RuntimeException;
class InwardQcService
{
 public function __construct(private NumberingService$numbering,private InventoryTransactionService$its){}
 public function create(int$c,GoodsReceipt$gr,array$lines,User$u):InwardInspection{if($lines===[]||(int)$gr->company_id!==$c||$gr->status!=='POSTED')throw new RuntimeException('Inspeksi tidak valid.');return DB::transaction(function()use($c,$gr,$lines,$u){$i=InwardInspection::create(['company_id'=>$c,'doc_no'=>$this->numbering->next($c,'FQC'),'goods_receipt_id'=>$gr->id,'result'=>'PENDING','created_by'=>$u->id]);$seen=[];$results=[];foreach($lines as$l){$gl=GrLine::query()->where('goods_receipt_id',$gr->id)->whereKey((int)$l['gr_line_id'])->first();if(!$gl)throw new RuntimeException('Inspection line bukan milik GR.');$rid=!empty($l['roll_id'])?(int)$l['roll_id']:null;if($gl->rolls()->exists()&&(!$rid||!$gl->rolls()->whereKey($rid)->exists()))throw new RuntimeException('Fabric inspection wajib menunjuk roll yang benar.');if(!$gl->rolls()->exists()&&$rid)throw new RuntimeException('Roll tidak valid.');$key=$gl->id.':'.($rid??'none');if(isset($seen[$key]))throw new RuntimeException('Inspection line duplikat.');$seen[$key]=1;$i->lines()->create($l);$results[]=$l['result'];}$i->result=in_array('FAIL',$results,true)?(in_array('PASS',$results,true)?'PARTIAL':'FAIL'):'PASS';$i->save();return$i->load('lines');});}
 public function finalize(InwardInspection$i,array$ignored,User$u):void{DB::transaction(function()use($i,$u){$locked=InwardInspection::withoutGlobalScopes()->whereKey($i->id)->lockForUpdate()->firstOrFail();if($locked->finalized_at)return;$gr=GoodsReceipt::withoutGlobalScopes()->where('company_id',$locked->company_id)->whereKey($locked->goods_receipt_id)->firstOrFail();$affected=[];foreach($locked->lines()->lockForUpdate()->get()as$il){$gl=GrLine::query()->where('goods_receipt_id',$gr->id)->whereKey($il->gr_line_id)->lockForUpdate()->firstOrFail();$affected[$gl->id]=1;$mat=$gl->material()->withoutGlobalScopes()->firstOrFail();$roll=null;$qty=(float)$gl->qty_received;$lot=null;$uom=$gl->uom_id;if($il->roll_id){$roll=FabricRoll::withoutGlobalScopes()->where('gr_line_id',$gl->id)->whereKey($il->roll_id)->lockForUpdate()->firstOrFail();$qty=(float)($roll->qty_use_actual??$roll->qty_meter_actual);$lot=$roll->lot_no;$uom=$roll->use_uom_id?:$mat->use_uom_id;if(!$uom)throw new RuntimeException('Use UOM fabric tidak tersedia.');}if($il->result==='PASS'){$this->its->releaseQualityHold((int)$locked->company_id,['material_id'=>$gl->material_id,'warehouse_id'=>$gr->warehouse_id,'lot_no'=>$lot,'roll_id'=>$roll?->id,'uom_id'=>$uom,'source_document_type'=>'inward_inspections','source_document_id'=>$locked->id,'source_document_line_id'=>$il->id],$qty,$u);$roll?->update(['status'=>'RELEASED']);}else$roll?->update(['status'=>'REJECTED_RETURNED']);}foreach(array_keys($affected)as$id){$gl=GrLine::query()->with('rolls')->findOrFail($id);if($gl->rolls->isEmpty())$gl->update(['status'=>$locked->lines()->where('gr_line_id',$id)->value('result')==='PASS'?'RELEASED':'REJECTED_RETURNED']);else{$s=$gl->rolls->pluck('status')->unique();$gl->update(['status'=>$s->count()===1?($s->first()==='RELEASED'?'RELEASED':'REJECTED_RETURNED'):'PARTIAL']);}}$locked->update(['finalized_at'=>now(),'updated_by'=>$u->id]);});}
 public function returnGoods(int$c,GoodsReceipt$gr,array$lines,string$reason,User$u):void{if($lines===[])throw new RuntimeException('Supplier return wajib punya line.');DB::transaction(function()use($c,$gr,$lines,$reason,$u){if((int)$gr->company_id!==$c||$gr->status!=='POSTED')throw new RuntimeException('GR return tidak valid.');$ret=$gr->purchaseOrder->supplier->returns()->create(['company_id'=>$c,'doc_no'=>$this->numbering->next($c,'GR'),'goods_receipt_id'=>$gr->id,'reason'=>$reason,'status'=>'SUBMITTED','created_by'=>$u->id]);$out=[];foreach($lines as$x){$gl=GrLine::query()->where('goods_receipt_id',$gr->id)->whereKey((int)($x['gr_line_id']??0))->first();if(!$gl)throw new RuntimeException('Return line bukan milik GR.');$mat=$gl->material()->withoutGlobalScopes()->firstOrFail();$roll=null;$qty=(float)$gl->qty_received;$lot=null;$uom=$gl->uom_id;$cost=(float)$gl->unit_price;if(!empty($x['roll_id'])){$roll=FabricRoll::withoutGlobalScopes()->where('gr_line_id',$gl->id)->whereKey((int)$x['roll_id'])->first();if(!$roll||$roll->status!=='REJECTED_RETURNED')throw new RuntimeException('Hanya roll rejected yang dapat diretur.');$qty=(float)($roll->qty_use_actual??$roll->qty_meter_actual);$lot=$roll->lot_no;$uom=$roll->use_uom_id?:$mat->use_uom_id;$cost=round(((float)$gl->unit_price*(float)$roll->qty_buy)/$qty,6);}elseif($gl->status!=='REJECTED_RETURNED')throw new RuntimeException('Hanya GR line rejected yang dapat diretur.');$out[]=['material_id'=>$gl->material_id,'warehouse_id'=>$gr->warehouse_id,'lot_no'=>$lot,'roll_id'=>$roll?->id,'qty'=>$qty,'uom_id'=>$uom,'unit_cost'=>$cost,'source_document_line_id'=>$gl->id];}$this->its->post('PURCHASE_RETURN',['company_id'=>$c,'source_document_type'=>'supplier_returns','source_document_id'=>$ret->id],$out,$u);});}
}
