<?php

use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::table('fabric_rolls',function(Blueprint$t){$t->unsignedBigInteger('use_uom_id')->nullable()->after('material_id');$t->decimal('qty_use_actual',18,4)->nullable()->after('qty_meter_actual');$t->decimal('qty_remaining_use',18,4)->nullable()->after('qty_remaining_meter');$t->foreign('use_uom_id','fk_fabric_rolls_use_uom')->references('id')->on('uoms')->restrictOnDelete();});
  Schema::table('marker_logs',function(Blueprint$t){$t->unsignedBigInteger('uom_id')->nullable()->after('roll_id');$t->decimal('marker_length_use',18,4)->nullable()->after('marker_length_m');$t->decimal('qty_fabric_used_use',18,4)->nullable()->after('qty_fabric_used_m');$t->foreign('uom_id','fk_marker_logs_uom')->references('id')->on('uoms')->restrictOnDelete();});
  Schema::table('fabric_returns',function(Blueprint$t){$t->unsignedBigInteger('uom_id')->nullable()->after('warehouse_id');$t->decimal('qty_returned_use',18,4)->nullable()->after('qty_returned_meter');$t->decimal('qty_dispatched_use',18,4)->nullable()->after('qty_returned_use');$t->decimal('qty_consumed_use',18,4)->nullable()->after('qty_dispatched_use');$t->foreign('uom_id','fk_fabric_returns_uom')->references('id')->on('uoms')->restrictOnDelete();$t->unique(['production_order_id','roll_id'],'uq_fabric_return_mo_roll');});
  DB::statement('UPDATE fabric_rolls fr JOIN materials m ON m.id=fr.material_id SET fr.use_uom_id=m.use_uom_id,fr.qty_use_actual=fr.qty_meter_actual,fr.qty_remaining_use=fr.qty_remaining_meter');
  DB::statement('UPDATE marker_logs ml JOIN fabric_rolls fr ON fr.id=ml.roll_id SET ml.uom_id=fr.use_uom_id,ml.marker_length_use=ml.marker_length_m,ml.qty_fabric_used_use=ml.qty_fabric_used_m');
  DB::statement('UPDATE fabric_returns r JOIN fabric_rolls fr ON fr.id=r.roll_id SET r.uom_id=fr.use_uom_id,r.qty_returned_use=r.qty_returned_meter');
  Schema::create('fabric_dispatch_balances',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('companies')->restrictOnDelete();$t->foreignId('production_order_id')->constrained('production_orders')->restrictOnDelete();$t->foreignId('roll_id')->constrained('fabric_rolls')->restrictOnDelete();$t->foreignId('warehouse_id')->constrained('warehouses')->restrictOnDelete();$t->foreignId('uom_id')->constrained('uoms')->restrictOnDelete();$t->decimal('qty_dispatched',18,4)->default(0);$t->decimal('qty_consumed',18,4)->default(0);$t->decimal('qty_returned',18,4)->default(0);$t->timestamps(6);$t->unique(['production_order_id','roll_id'],'uq_fabric_dispatch_mo_roll');$t->index(['company_id','roll_id'],'idx_fabric_dispatch_company_roll');});
  DB::statement("INSERT INTO fabric_dispatch_balances(company_id,production_order_id,roll_id,warehouse_id,uom_id,qty_dispatched,qty_consumed,qty_returned,created_at,updated_at) SELECT mi.company_id,mi.production_order_id,mil.roll_id,mi.warehouse_id,mil.uom_id,SUM(mil.qty),COALESCE((SELECT SUM(COALESCE(ml.qty_fabric_used_use,ml.qty_fabric_used_m)) FROM marker_logs ml JOIN cut_orders co ON co.id=ml.cut_order_id WHERE co.production_order_id=mi.production_order_id AND ml.roll_id=mil.roll_id),0),COALESCE((SELECT SUM(COALESCE(fr.qty_returned_use,fr.qty_returned_meter)) FROM fabric_returns fr WHERE fr.production_order_id=mi.production_order_id AND fr.roll_id=mil.roll_id),0),MIN(mi.created_at),MAX(mi.updated_at) FROM material_issue_lines mil JOIN material_issues mi ON mi.id=mil.material_issue_id WHERE mil.roll_id IS NOT NULL AND mi.status='POSTED' GROUP BY mi.company_id,mi.production_order_id,mil.roll_id,mi.warehouse_id,mil.uom_id");
  DB::statement('ALTER TABLE fabric_dispatch_balances ADD CONSTRAINT chk_fabric_dispatch_qty CHECK (qty_dispatched>=0 AND qty_consumed>=0 AND qty_returned>=0 AND qty_consumed+qty_returned<=qty_dispatched)');
 }
 public function down():void{Schema::dropIfExists('fabric_dispatch_balances');Schema::table('fabric_returns',function(Blueprint$t){$t->dropUnique('uq_fabric_return_mo_roll');$t->dropForeign('fk_fabric_returns_uom');$t->dropColumn(['uom_id','qty_returned_use','qty_dispatched_use','qty_consumed_use']);});Schema::table('marker_logs',function(Blueprint$t){$t->dropForeign('fk_marker_logs_uom');$t->dropColumn(['uom_id','marker_length_use','qty_fabric_used_use']);});Schema::table('fabric_rolls',function(Blueprint$t){$t->dropForeign('fk_fabric_rolls_use_uom');$t->dropColumn(['use_uom_id','qty_use_actual','qty_remaining_use']);});}
};
