<?php

use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('tax_codes',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('companies')->restrictOnDelete();$t->string('code',32);$t->string('name');$t->string('kind',32);$t->decimal('rate_pct',9,6);$t->boolean('is_active')->default(true);$t->timestamps(6);$t->unsignedBigInteger('created_by')->nullable();$t->unsignedBigInteger('updated_by')->nullable();$t->unique(['company_id','code'],'uq_tax_codes_company_code');$t->index(['company_id','kind','is_active'],'idx_tax_codes_kind');});DB::statement("ALTER TABLE tax_codes ADD CONSTRAINT chk_tax_codes_kind CHECK (kind IN ('OUTPUT_TAX','INPUT_TAX','WITHHOLDING_RECEIVABLE','WITHHOLDING_PAYABLE'))");DB::statement('ALTER TABLE tax_codes ADD CONSTRAINT chk_tax_codes_rate CHECK (rate_pct >= 0 AND rate_pct <= 100)');
  Schema::create('finance_tax_lines',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('companies')->restrictOnDelete();$t->string('document_type',16);$t->unsignedBigInteger('document_id');$t->foreignId('tax_code_id')->constrained('tax_codes')->restrictOnDelete();$t->string('tax_code',32);$t->string('kind',32);$t->decimal('taxable_base',19,4);$t->decimal('rate_pct',9,6);$t->decimal('amount',19,4);$t->timestamps(6);$t->unsignedBigInteger('created_by')->nullable();$t->unique(['document_type','document_id','tax_code_id'],'uq_finance_tax_document_code');$t->index(['company_id','document_type','document_id'],'idx_finance_tax_document');});DB::statement("ALTER TABLE finance_tax_lines ADD CONSTRAINT chk_finance_tax_document CHECK (document_type IN ('AR_INVOICE','AP_INVOICE'))");DB::statement('ALTER TABLE finance_tax_lines ADD CONSTRAINT chk_finance_tax_amount CHECK (taxable_base >= 0 AND rate_pct >= 0 AND amount >= 0)');
  Schema::table('ar_invoices',function(Blueprint$t){$t->decimal('subtotal_amount',19,4)->default(0)->after('exchange_rate');$t->decimal('tax_amount',19,4)->default(0)->after('subtotal_amount');$t->decimal('withholding_amount',19,4)->default(0)->after('tax_amount');$t->decimal('base_amount',19,4)->default(0)->after('total_amount');$t->timestamp('finance_finalized_at',6)->nullable()->after('base_amount');});DB::statement('UPDATE ar_invoices SET subtotal_amount=total_amount,base_amount=total_amount*exchange_rate,finance_finalized_at=created_at');
  Schema::table('supplier_invoices',function(Blueprint$t){$t->foreignId('currency_id')->nullable()->after('due_date')->constrained('currencies')->restrictOnDelete();$t->decimal('exchange_rate',18,6)->default(1)->after('currency_id');$t->decimal('subtotal_amount',19,4)->default(0)->after('exchange_rate');$t->decimal('tax_amount',19,4)->default(0)->after('subtotal_amount');$t->decimal('withholding_amount',19,4)->default(0)->after('tax_amount');$t->decimal('base_amount',19,4)->default(0)->after('total_amount');$t->timestamp('finance_finalized_at',6)->nullable()->after('base_amount');});DB::statement('UPDATE supplier_invoices SET subtotal_amount=total_amount,base_amount=total_amount');
  foreach(['ar_payments','ap_payments']as$table)Schema::table($table,function(Blueprint$t){$t->foreignId('currency_id')->nullable()->after('payment_date')->constrained('currencies')->restrictOnDelete();$t->decimal('exchange_rate',18,6)->default(1)->after('currency_id');$t->decimal('base_amount',19,4)->default(0)->after('amount');$t->decimal('realized_fx_amount',19,4)->default(0)->after('base_amount');});DB::statement('UPDATE ar_payments p JOIN ar_invoices i ON i.id=p.ar_invoice_id SET p.currency_id=i.currency_id,p.exchange_rate=i.exchange_rate,p.base_amount=p.amount*i.exchange_rate');DB::statement('UPDATE ap_payments p JOIN supplier_invoices i ON i.id=p.supplier_invoice_id SET p.currency_id=i.currency_id,p.exchange_rate=i.exchange_rate,p.base_amount=p.amount*i.exchange_rate');
  DB::statement('ALTER TABLE ar_invoices ADD CONSTRAINT chk_ar_invoice_finance_amounts CHECK (exchange_rate > 0 AND subtotal_amount >= 0 AND tax_amount >= 0 AND withholding_amount >= 0 AND total_amount > 0 AND base_amount >= 0)');DB::statement('ALTER TABLE supplier_invoices ADD CONSTRAINT chk_ap_invoice_fx_amounts CHECK (exchange_rate > 0 AND subtotal_amount >= 0 AND tax_amount >= 0 AND withholding_amount >= 0 AND total_amount > 0 AND base_amount >= 0)');DB::statement('ALTER TABLE ar_payments ADD CONSTRAINT chk_ar_payment_fx CHECK (exchange_rate > 0 AND base_amount >= 0)');DB::statement('ALTER TABLE ap_payments ADD CONSTRAINT chk_ap_payment_fx CHECK (exchange_rate > 0 AND base_amount >= 0)');
 }
 public function down():void{DB::statement('ALTER TABLE ap_payments DROP CHECK chk_ap_payment_fx');DB::statement('ALTER TABLE ar_payments DROP CHECK chk_ar_payment_fx');DB::statement('ALTER TABLE supplier_invoices DROP CHECK chk_ap_invoice_fx_amounts');DB::statement('ALTER TABLE ar_invoices DROP CHECK chk_ar_invoice_finance_amounts');foreach(['ap_payments','ar_payments']as$table)Schema::table($table,function(Blueprint$t){$t->dropForeign(['currency_id']);$t->dropColumn(['currency_id','exchange_rate','base_amount','realized_fx_amount']);});Schema::table('supplier_invoices',function(Blueprint$t){$t->dropForeign(['currency_id']);$t->dropColumn(['currency_id','exchange_rate','subtotal_amount','tax_amount','withholding_amount','base_amount','finance_finalized_at']);});Schema::table('ar_invoices',fn(Blueprint$t)=>$t->dropColumn(['subtotal_amount','tax_amount','withholding_amount','base_amount','finance_finalized_at']));Schema::dropIfExists('finance_tax_lines');Schema::dropIfExists('tax_codes');}
};
