<?php

namespace Modules\ShopFloor\Services;

use Carbon\CarbonImmutable;use Illuminate\Support\Facades\DB;use Modules\Core\Models\User;use Modules\Core\Services\AuditService;use Modules\Cutting\Models\Bundle;use Modules\Production\Models\ProductionOrder;use Modules\ShopFloor\Exceptions\ScanConflictException;use Modules\ShopFloor\Models\ProductionScan;use Modules\ShopFloor\Models\ShopfloorDevice;use Modules\ShopFloor\Models\WipTransfer;use RuntimeException;use Throwable;
class ScanService
{
 public function __construct(private AuditService$audit){}
 public function scan(int$c,string$bundleNo,array$data,User$u):ProductionScan{return DB::transaction(fn()=>$this->execute($c,$bundleNo,$data,$u));}
 public function syncScan(int$c,array$data,User$u,ShopfloorDevice$device):array
 {
  $event=trim((string)($data['client_event_id']??''));if($event==='')throw new RuntimeException('client_event_id wajib tersedia.');$clientAt=$this->clientTime((string)($data['client_scanned_at']??''));$payload=$this->canonicalPayload($data,$clientAt);$hash=hash('sha256',json_encode($payload,JSON_THROW_ON_ERROR));
  return DB::transaction(function()use($c,$data,$u,$device,$event,$clientAt,$hash){$lockedDevice=ShopfloorDevice::withoutGlobalScopes()->where('company_id',$c)->whereKey($device->id)->where('status','ACTIVE')->lockForUpdate()->first();if(!$lockedDevice)throw new RuntimeException('Perangkat tidak aktif.');$existing=ProductionScan::withoutGlobalScopes()->where('device_id',$lockedDevice->id)->where('client_event_id',$event)->lockForUpdate()->first();if($existing){if(hash_equals((string)$existing->payload_hash,$hash))return['status'=>'replayed','scan'=>$existing];throw new ScanConflictException('client_event_id telah dipakai dengan payload berbeda.',(int)($existing->bundle_version??0),['scan_id'=>$existing->id]);}$input=$data;$input['client_scanned_at']=$clientAt;$input['payload_hash']=$hash;$input['device_id']=$lockedDevice->id;$scan=$this->execute($c,(string)$data['bundle_no'],$input,$u);DB::table('shopfloor_devices')->where('id',$lockedDevice->id)->update(['last_seen_at'=>now(),'updated_at'=>now()]);return['status'=>'applied','scan'=>$scan];});
 }
 private function execute(int$c,string$bundleNo,array$d,User$u):ProductionScan
 {
  $this->access($u,$c);$direction=strtoupper((string)($d['direction']??''));$stage=strtoupper((string)($d['stage']??''));if(!in_array($direction,ProductionScan::DIRECTIONS,true)||!in_array($stage,ProductionScan::STAGES,true))throw new RuntimeException('Direction atau stage scan tidak valid.');
  $bundle=Bundle::withoutGlobalScopes()->with('cutOutput.lay.cutOrder')->where('company_id',$c)->where('bundle_no',$bundleNo)->where('status','ACTIVE')->lockForUpdate()->first();if(!$bundle)throw new RuntimeException('Bundle aktif tidak ditemukan pada company ini.');$version=(int)($bundle->scan_version??0);if(array_key_exists('expected_bundle_version',$d)&&(int)$d['expected_bundle_version']!==$version)throw new ScanConflictException('Versi bundle sudah berubah. Sinkronkan state terbaru sebelum retry.',$version,$this->snapshot($bundle));
  $mo=ProductionOrder::withoutGlobalScopes()->where('company_id',$c)->whereKey($bundle->production_order_id)->lockForUpdate()->firstOrFail();if(!in_array($mo->status,['CUTTING','SEWING','FINISHING'],true))throw new RuntimeException("Status MO {$mo->status} tidak mengizinkan scan shop floor.");if($stage==='FINISHING'&&$mo->status!=='FINISHING')throw new RuntimeException("Status MO {$mo->status} tidak mengizinkan transaksi Finishing.");
  $op=(int)($d['operation_id']??0);$ops=$mo->routingVersion->operations()->orderBy('seq')->get();$routing=$ops->firstWhere('operation_id',$op);if(!$routing)throw new RuntimeException("Operasi #{$op} tidak ada di routing snapshot MO.");$line=$d['line_id']??$mo->line_id;if($line!==null&&!DB::table('lines')->where('company_id',$c)->where('id',$line)->exists())throw new RuntimeException('Line scan tidak ditemukan pada company ini.');$employee=$d['employee_id']??null;if($employee!==null&&!DB::table('employees')->where('company_id',$c)->where('id',$employee)->exists())throw new RuntimeException('Employee scan tidak ditemukan pada company ini.');
  $priorSewing=ProductionScan::withoutGlobalScopes()->where('bundle_id',$bundle->id)->where('stage','SEWING')->exists();$firstSewingInput=$stage==='SEWING'&&$direction==='IN'&&!$priorSewing;if($firstSewingInput){if($bundle->current_stage!=='CUTTING')throw new RuntimeException('Bundle sudah dikonsumsi atau bukan WIP CUTTING.');if($bundle->cut_output_id!==null&&($bundle->cutOutput?->lay?->status!=='COMPLETED'))throw new RuntimeException('Bundle belum eligible: parent Lay belum COMPLETED.');}
  $same=ProductionScan::withoutGlobalScopes()->where('bundle_id',$bundle->id)->where('operation_id',$op)->where('stage',$stage)->where('direction',$direction)->lockForUpdate()->first();if($same)throw new RuntimeException("Bundle {$bundleNo}: duplicate {$direction} pada operasi dan stage yang sama.");if($stage==='FINISHING'){$this->assertFinishingSource($c,$bundle,$routing,$ops,$direction);}$last=ProductionScan::withoutGlobalScopes()->where('bundle_id',$bundle->id)->where('operation_id',$op)->where('stage',$stage)->orderByDesc('scanned_at')->orderByDesc('id')->lockForUpdate()->first();
  if($direction==='OUT'){if(!$last||$last->direction!=='IN')throw new RuntimeException("Bundle {$bundleNo}: OUT tanpa IN pada operasi ini.");if(abs((float)($last->qty??$bundle->qty)-(float)$bundle->qty)>0.0001)throw new RuntimeException(ucfirst(strtolower($stage)).' Output melebihi atau tidak cocok dengan valid Input.');}else{if($last)throw new RuntimeException("Bundle {$bundleNo}: operasi/stage ini sudah pernah dimulai.");if($stage==='SEWING'){$prev=$ops->where('seq','<',$routing->seq)->sortByDesc('seq')->first();if($prev&&!ProductionScan::withoutGlobalScopes()->where('bundle_id',$bundle->id)->where('operation_id',$prev->operation_id)->where('stage','SEWING')->where('direction','OUT')->exists())throw new RuntimeException("Bundle {$bundleNo}: belum selesai operasi sebelumnya (seq {$prev->seq}).");}else{$done=ProductionScan::withoutGlobalScopes()->where('bundle_id',$bundle->id)->where('stage','SEWING')->where('direction','OUT')->pluck('operation_id')->unique();if($ops->pluck('operation_id')->diff($done)->isNotEmpty())throw new RuntimeException("Bundle {$bundleNo}: seluruh operasi sewing wajib OUT sebelum finishing.");}}
  $next=$version+1;$client=$d['client_scanned_at']??null;$qty=(float)$bundle->qty;$scan=ProductionScan::create(['company_id'=>$c,'bundle_id'=>$bundle->id,'operation_id'=>$op,'production_order_id'=>$mo->id,'line_id'=>$line,'employee_id'=>$employee,'device_id'=>$d['device_id']??null,'client_event_id'=>$d['client_event_id']??null,'bundle_version'=>$next,'direction'=>$direction,'stage'=>$stage,'qty'=>$qty,'scanned_at'=>$client?:now(),'client_scanned_at'=>$client,'received_at'=>isset($d['device_id'])?now():null,'payload_hash'=>$d['payload_hash']??null]);
  $completedSewing=$stage==='SEWING'&&$direction==='OUT'&&$ops->pluck('operation_id')->diff(ProductionScan::withoutGlobalScopes()->where('bundle_id',$bundle->id)->where('stage','SEWING')->where('direction','OUT')->pluck('operation_id')->unique())->isEmpty();$newStage=$completedSewing?'FINISHING':$stage;$bundle->update(['current_stage'=>$newStage,'scan_version'=>$next]);if($firstSewingInput)$this->transfer($bundle,$scan,'CUTTING','SEWING',$u);if($completedSewing)$this->transfer($bundle,$scan,'SEWING','FINISHING',$u);$this->audit->record('create',$scan,after:['bundle_no'=>$bundleNo,'direction'=>$direction,'stage'=>$stage,'qty'=>$qty]);$this->advance($mo,$stage);return$scan->load('wipTransfer');
 }
 private function assertFinishingSource(int$c,Bundle$b,mixed$routing,mixed$ops,string$direction):void
 {
  if($b->current_stage!=='FINISHING')throw new RuntimeException('Bundle bukan WIP FINISHING yang eligible.');$source=WipTransfer::withoutGlobalScopes()->where('company_id',$c)->where('production_order_id',$b->production_order_id)->where('bundle_id',$b->id)->where('from_stage','SEWING')->where('to_stage','FINISHING')->lockForUpdate()->first();if(!$source)throw new RuntimeException('Finishing Input tidak memiliki source WIP transfer Sewing ke Finishing.');if(abs((float)$source->qty-(float)$b->qty)>0.0001)throw new RuntimeException('Quantity Finishing Input tidak cocok dengan available Sewing WIP.');
  if($direction==='IN'){$lastScan=ProductionScan::withoutGlobalScopes()->where('bundle_id',$b->id)->where('stage','FINISHING')->orderByDesc('scanned_at')->orderByDesc('id')->lockForUpdate()->first();if($lastScan&&$lastScan->direction!=='OUT')throw new RuntimeException('Operasi Finishing sebelumnya belum OUT.');if($lastScan){$lastRouting=$ops->firstWhere('operation_id',$lastScan->operation_id);if(!$lastRouting||$routing->seq<=$lastRouting->seq)throw new RuntimeException('Urutan operasi Finishing harus maju mengikuti routing snapshot MO.');}}
 }
 private function transfer(Bundle$b,ProductionScan$s,string$from,string$to,User$u):void{$transfer=WipTransfer::create(['company_id'=>$b->company_id,'production_order_id'=>$b->production_order_id,'bundle_id'=>$b->id,'source_scan_id'=>$s->id,'from_stage'=>$from,'to_stage'=>$to,'qty'=>$b->qty,'transferred_at'=>$s->scanned_at,'created_by'=>$u->id,'created_at'=>now()]);$this->audit->record('create',$transfer,after:['bundle_no'=>$b->bundle_no,'from_stage'=>$from,'to_stage'=>$to,'qty'=>(float)$b->qty]);}
 public function eligibleBundles(int$c,?int$mo=null):array{$q=Bundle::withoutGlobalScopes()->where('company_id',$c)->where('status','ACTIVE')->where('current_stage','CUTTING')->with(['cutOutput.lay','cutOrderLine']);if($mo)$q->where('production_order_id',$mo);return$q->orderBy('bundle_no')->get()->filter(fn(Bundle$b)=>$b->cut_output_id===null||$b->cutOutput?->lay?->status==='COMPLETED')->map(fn(Bundle$b)=>['bundle_no'=>$b->bundle_no,'qty'=>(float)$b->qty,'production_order_id'=>$b->production_order_id,'cut_output_id'=>$b->cut_output_id,'lineage_complete'=>$b->cut_output_id!==null])->values()->all();}
 public function eligibleFinishingBundles(int$c,?int$mo=null):array{$q=Bundle::withoutGlobalScopes()->where('company_id',$c)->where('status','ACTIVE')->where('current_stage','FINISHING')->whereIn('production_order_id',ProductionOrder::withoutGlobalScopes()->where('company_id',$c)->where('status','FINISHING')->select('id'));if($mo)$q->where('production_order_id',$mo);return$q->orderBy('bundle_no')->get()->map(function(Bundle$b)use($c){$source=WipTransfer::withoutGlobalScopes()->where('company_id',$c)->where('production_order_id',$b->production_order_id)->where('bundle_id',$b->id)->where('from_stage','SEWING')->where('to_stage','FINISHING')->first();if(!$source||abs((float)$source->qty-(float)$b->qty)>0.0001)return null;$last=ProductionScan::withoutGlobalScopes()->where('company_id',$c)->where('bundle_id',$b->id)->where('stage','FINISHING')->orderByDesc('scanned_at')->orderByDesc('id')->first();return['bundle_no'=>$b->bundle_no,'qty'=>(float)$b->qty,'available_qty'=>(float)$source->qty,'production_order_id'=>$b->production_order_id,'source_wip_transfer_id'=>$source->id,'last_finishing_operation_id'=>$last?->operation_id,'last_finishing_direction'=>$last?->direction,'lineage_complete'=>$b->cut_output_id!==null];})->filter()->values()->all();}
 public function lineage(int$c,string$bundleNo):array{$b=Bundle::withoutGlobalScopes()->where('company_id',$c)->where('bundle_no',$bundleNo)->with(['wipTransfers.sourceScan.operation','scans.operation','cutOutput.lay.rolls.fabricRoll'])->first();if(!$b)throw new RuntimeException('Bundle tidak ditemukan pada company ini.');$finishingInputs=$b->scans->where('stage','FINISHING')->where('direction','IN')->values();$finishingOutputs=$b->scans->where('stage','FINISHING')->where('direction','OUT')->values();$qcPass=DB::table('qc_inspections')->where('company_id',$c)->where('production_order_id',$b->production_order_id)->where('stage','FINAL')->where('verdict','PASS')->exists();return['bundle'=>$b,'sewing_inputs'=>$b->scans->where('stage','SEWING')->where('direction','IN')->values(),'sewing_outputs'=>$b->scans->where('stage','SEWING')->where('direction','OUT')->values(),'wip_transfers'=>$b->wipTransfers,'finishing_inputs'=>$finishingInputs,'finishing_outputs'=>$finishingOutputs,'finishing_source'=>$b->wipTransfers->first(fn($t)=>$t->from_stage==='SEWING'&&$t->to_stage==='FINISHING'),'packing_boundary'=>['finishing_output_available'=>$finishingOutputs->isNotEmpty(),'qc_final_pass_required'=>true,'qc_final_pass'=>$qcPass,'direct_bundle_to_carton_defined'=>false,'status'=>'NOT_DEFINED']];}
 private function clientTime(string$value):CarbonImmutable{try{$at=CarbonImmutable::parse($value);}catch(Throwable){throw new RuntimeException('client_scanned_at tidak valid.');}$now=CarbonImmutable::now();$max=max(1,(int)config('shopfloor.offline_max_age_days',7));$skew=max(0,(int)config('shopfloor.clock_skew_minutes',5));if($at->lt($now->subDays($max)))throw new RuntimeException("Event offline lebih lama dari {$max} hari.");if($at->gt($now->addMinutes($skew)))throw new RuntimeException('Jam perangkat terlalu jauh di masa depan.');return$at;}
 private function canonicalPayload(array$d,CarbonImmutable$at):array{$p=['bundle_no'=>(string)($d['bundle_no']??''),'operation_id'=>(int)($d['operation_id']??0),'direction'=>strtoupper((string)($d['direction']??'')),'stage'=>strtoupper((string)($d['stage']??'')),'line_id'=>isset($d['line_id'])?(int)$d['line_id']:null,'employee_id'=>isset($d['employee_id'])?(int)$d['employee_id']:null,'expected_bundle_version'=>(int)($d['expected_bundle_version']??-1),'client_scanned_at'=>$at->utc()->format('Y-m-d\TH:i:s.u\Z')];ksort($p);return$p;}
 private function snapshot(Bundle$b):array{return['bundle_no'=>$b->bundle_no,'current_stage'=>$b->current_stage,'status'=>$b->status,'scan_version'=>(int)($b->scan_version??0)];}
 public function wipByStage(int$c,int$mo):array{if(!ProductionOrder::withoutGlobalScopes()->where('company_id',$c)->whereKey($mo)->exists())throw new RuntimeException('MO tidak ditemukan pada company ini.');return Bundle::withoutGlobalScopes()->where('company_id',$c)->where('production_order_id',$mo)->where('status','ACTIVE')->selectRaw('current_stage,COUNT(*) bundle_count,SUM(qty) pcs')->groupBy('current_stage')->get()->mapWithKeys(fn($r)=>[$r->current_stage=>['bundles'=>(int)$r->bundle_count,'pcs'=>(float)$r->pcs]])->all();}
 public function dailyOutput(int$c,int$line,string$date):array{if(!DB::table('lines')->where('company_id',$c)->where('id',$line)->exists())throw new RuntimeException('Line tidak ditemukan pada company ini.');return ProductionScan::withoutGlobalScopes()->where('production_scans.company_id',$c)->where('production_scans.line_id',$line)->where('direction','OUT')->whereDate('scanned_at',$date)->join('bundles','bundles.id','=','production_scans.bundle_id')->selectRaw('production_scans.stage,production_scans.operation_id,SUM(COALESCE(production_scans.qty,bundles.qty)) pcs,COUNT(DISTINCT production_scans.bundle_id) bundles')->groupBy('production_scans.stage','production_scans.operation_id')->get()->all();}
 private function advance(ProductionOrder$mo,string$stage):void{$target=$stage==='SEWING'?'SEWING':'FINISHING';$order=['PLANNED'=>0,'RELEASED'=>1,'CUTTING'=>2,'SEWING'=>3,'FINISHING'=>4,'QC'=>5,'PACKED'=>6,'CLOSED'=>7];if(($order[$target]??0)>($order[$mo->status]??0))$mo->update(['status'=>$target]);}
 private function access(User$u,int$c):void{if((int)$u->company_id!==$c&&!$u->companies()->whereKey($c)->exists())throw new RuntimeException('User tidak memiliki akses ke company scan.');}
}
