<?php

namespace Modules\Finance\Services;
use Illuminate\Support\Facades\DB;use Modules\Core\Approval\ApprovalEngine;use Modules\Core\Models\ApprovalRequest;use Modules\Core\Models\User;use Modules\Core\Services\AuditService;use Modules\Finance\Models\AccountingCorrection;use Modules\Finance\Models\AccountMapping;use Modules\Finance\Models\Journal;use RuntimeException;
class AccountingCorrectionService
{
 public const DOC_TYPE='ACCOUNTING_CORRECTION';
 public function __construct(private JournalService$journals,private ApprovalEngine$approval,private AuditService$audit){}
 public function request(Journal$journal,float$corrected,string$reason,int$version,User$user):array
 {
  $reason=trim($reason);if($corrected<0||$reason===''||$version<1)throw new RuntimeException('D-11 corrected amount, reason, and version are invalid.');
  return DB::transaction(function()use($journal,$corrected,$reason,$version,$user):array{
   $j=Journal::withoutGlobalScopes()->with('lines')->whereKey($journal->id)->lockForUpdate()->firstOrFail();$this->access($user,(int)$j->company_id);$authority=$this->authority($j);$mapping=$this->mapping($j);$period=$this->period((int)$j->company_id,$j->period);$difference=round($corrected-(float)$j->total_debit,4);
   $mode=$period->status==='OPEN'?'OPEN_REPOST':'CLOSED_ADJUST';if($mode==='OPEN_REPOST'&&abs($difference)>.0001&&$corrected<=0)throw new RuntimeException('D-11 OPEN correction to zero cannot create the mandatory corrected repost under existing GL constraints.');
   $targetPeriod=null;$targetDate=null;if($mode==='CLOSED_ADJUST'&&abs($difference)>.0001){[$targetPeriod,$targetDate]=$this->currentOpenPeriod((int)$j->company_id);}
   $hash=$this->hash($j,$mapping,$authority,$corrected,$difference,$reason,$version,$period->status,$mode,$targetPeriod,$targetDate);
   $existing=AccountingCorrection::withoutGlobalScopes()->with('approvalRequest','originalJournal.lines','reversalJournal.lines','correctedJournal.lines','adjustmentJournal.lines')->where('company_id',$j->company_id)->where('original_journal_id',$j->id)->where('correction_version',$version)->lockForUpdate()->first();
   if($existing){if(!hash_equals($existing->source_hash,$hash))throw new RuntimeException('D-11 IDEMPOTENCY CONFLICT: correction version has a different payload.');return['created'=>false,'correction'=>$existing];}
   if(AccountingCorrection::withoutGlobalScopes()->where('company_id',$j->company_id)->where('original_journal_id',$j->id)->whereIn('status',['REQUESTED','APPROVED','REVERSAL_POSTED','CORRECTED_REPOST_POSTED','ADJUSTMENT_POSTED','POSTED'])->lockForUpdate()->exists())throw new RuntimeException('D-11 another active or posted correction already targets the original journal.');
   $status=abs($difference)<=.0001?'NO_CHANGE':'REQUESTED';$c=AccountingCorrection::create(['company_id'=>$j->company_id,'original_journal_id'=>$j->id,'original_source_type'=>$j->source_document_type,'original_source_id'=>$j->source_document_id,'original_event'=>$j->event,'original_gl_period'=>$j->period,'original_posting_date'=>$j->journal_date,'original_amount'=>$j->total_debit,'corrected_amount'=>$corrected,'adjustment_amount'=>$difference,'currency'=>$authority['currency'],'period_state'=>$period->status,'correction_mode'=>$mode,'reason'=>$reason,'status'=>$status,'account_mapping_id'=>$mapping->id,'debit_account_id'=>$mapping->debit_account_id,'credit_account_id'=>$mapping->credit_account_id,'adjustment_period'=>$targetPeriod,'adjustment_posting_date'=>$targetDate,'correction_version'=>$version,'source_hash'=>$hash,'requested_by'=>$user->id,'requested_at'=>now(),'created_at'=>now()]);
   if($status==='NO_CHANGE'){$this->audit->record('create',$c,after:['decision'=>'NO_CHANGE','original_journal_id'=>$j->id,'source_hash'=>$hash]);return['created'=>true,'correction'=>$c];}
   $approval=$this->approval->submit($c,self::DOC_TYPE,$user);DB::table('accounting_corrections')->where('id',$c->id)->where('company_id',$j->company_id)->update(['approval_request_id'=>$approval->id]);$c=$this->load($c->id);$this->audit->record('submit',$c,after:['approval_request_id'=>$approval->id,'mode'=>$mode,'source_hash'=>$hash]);return['created'=>true,'correction'=>$c];
  });
 }
 public function approve(AccountingCorrection$correction,User$user,?string$note=null):AccountingCorrection
 {
  return DB::transaction(function()use($correction,$user,$note):AccountingCorrection{$c=AccountingCorrection::withoutGlobalScopes()->whereKey($correction->id)->lockForUpdate()->firstOrFail();$this->access($user,(int)$c->company_id);if($c->status==='APPROVED'||$c->status==='POSTED')return$this->load($c->id);if($c->status!=='REQUESTED')throw new RuntimeException('D-11 correction is not REQUESTED.');$r=ApprovalRequest::withoutGlobalScopes()->where('company_id',$c->company_id)->whereKey($c->approval_request_id)->where('doc_type',self::DOC_TYPE)->where('doc_id',$c->id)->lockForUpdate()->firstOrFail();$approved=$this->approval->approve($r,$user,$note);if($approved->status==='APPROVED')DB::table('accounting_corrections')->where('id',$c->id)->where('status','REQUESTED')->update(['status'=>'APPROVED','approved_by'=>$user->id,'approved_at'=>$approved->completed_at??now()]);return$this->load($c->id);});
 }
 public function reject(AccountingCorrection$correction,User$user,?string$note=null):AccountingCorrection
 {
  return DB::transaction(function()use($correction,$user,$note):AccountingCorrection{$c=AccountingCorrection::withoutGlobalScopes()->whereKey($correction->id)->lockForUpdate()->firstOrFail();$this->access($user,(int)$c->company_id);if($c->status!=='REQUESTED')throw new RuntimeException('D-11 correction is not REQUESTED.');$r=ApprovalRequest::withoutGlobalScopes()->where('company_id',$c->company_id)->whereKey($c->approval_request_id)->where('doc_type',self::DOC_TYPE)->where('doc_id',$c->id)->lockForUpdate()->firstOrFail();$this->approval->reject($r,$user,$note);DB::table('accounting_corrections')->where('id',$c->id)->update(['status'=>'REJECTED','approved_by'=>$user->id,'approved_at'=>now()]);return$this->load($c->id);});
 }
 public function post(AccountingCorrection$correction,User$user):array
 {
  return DB::transaction(function()use($correction,$user):array{$c=AccountingCorrection::withoutGlobalScopes()->whereKey($correction->id)->lockForUpdate()->firstOrFail();$this->access($user,(int)$c->company_id);if($c->status==='NO_CHANGE')return['created'=>false,'result'=>'NO_CHANGE','correction'=>$this->load($c->id)];if($c->status==='POSTED')return['created'=>false,'result'=>'POSTED_REPLAY','correction'=>$this->load($c->id)];if($c->status!=='APPROVED')throw new RuntimeException('D-11 correction requires completed ApprovalEngine approval before posting.');
   $approval=ApprovalRequest::withoutGlobalScopes()->where('company_id',$c->company_id)->whereKey($c->approval_request_id)->where('status','APPROVED')->where('is_active',false)->lockForUpdate()->first();if(!$approval)throw new RuntimeException('D-11 approved request evidence is missing.');$j=Journal::withoutGlobalScopes()->with('lines')->where('company_id',$c->company_id)->whereKey($c->original_journal_id)->lockForUpdate()->firstOrFail();$authority=$this->authority($j);$mapping=$this->mapping($j);$period=$this->period((int)$c->company_id,$j->period);$targetPeriod=$c->adjustment_period;$targetDate=$c->adjustment_posting_date?->toDateString();$hash=$this->hash($j,$mapping,$authority,(float)$c->corrected_amount,(float)$c->adjustment_amount,$c->reason,(int)$c->correction_version,$period->status,$c->correction_mode,$targetPeriod,$targetDate);if(!hash_equals($c->source_hash,$hash))throw new RuntimeException('D-11 source changed after approval.');
   $reversal=null;$repost=null;$adjustment=null;if($c->correction_mode==='OPEN_REPOST'){
    if($period->status!=='OPEN'||$c->period_state!=='OPEN')throw new RuntimeException('D-11 original period is no longer OPEN; approved mode cannot change silently.');if((float)$c->corrected_amount<=0)throw new RuntimeException('D-11 mandatory corrected repost amount must be greater than zero.');if(Journal::withoutGlobalScopes()->where('reverses_journal_id',$j->id)->exists())throw new RuntimeException('D-11 original journal already has a reversal.');$revLines=$j->lines->map(fn($l)=>['coa_id'=>$l->coa_id,'debit'=>(float)$l->credit,'credit'=>(float)$l->debit,'memo'=>'D-11 reversal of '.$j->doc_no.' / correction '.$c->id])->all();$reversal=$this->journals->post((int)$c->company_id,['period'=>$j->period,'journal_date'=>$j->journal_date->toDateString(),'source'=>'AUTO','event'=>'D11_REVERSAL','source_document_type'=>'accounting_corrections','source_document_id'=>$c->id,'posting_key'=>$this->key($c,'REVERSAL'),'description'=>'D-11 append-only reversal '.$j->doc_no],$revLines,$user);DB::table('journals')->where('id',$reversal->id)->update(['reverses_journal_id'=>$j->id]);DB::table('accounting_corrections')->where('id',$c->id)->update(['status'=>'REVERSAL_POSTED','reversal_journal_id'=>$reversal->id]);
    $amount=(float)$c->corrected_amount;$repost=$this->journals->post((int)$c->company_id,['period'=>$j->period,'journal_date'=>$j->journal_date->toDateString(),'source'=>'AUTO','event'=>'D11_CORRECTED_REPOST','source_document_type'=>'accounting_corrections','source_document_id'=>$c->id,'posting_key'=>$this->key($c,'REPOST'),'description'=>'D-11 corrected repost for '.$j->doc_no],$this->mappedLines($c,$amount,false),$user);DB::table('accounting_corrections')->where('id',$c->id)->update(['status'=>'CORRECTED_REPOST_POSTED','corrected_journal_id'=>$repost->id]);
   }elseif($c->correction_mode==='CLOSED_ADJUST'){
    if($period->status!=='CLOSED'||$c->period_state!=='CLOSED')throw new RuntimeException('D-11 closed-period source state changed.');[$current]=$this->currentOpenPeriod((int)$c->company_id);if($current!==$c->adjustment_period||$targetDate===null||substr($targetDate,0,7)!==$current)throw new RuntimeException('D-11 approved current-period target is no longer current; request a new correction.');$diff=(float)$c->adjustment_amount;$adjustment=$this->journals->post((int)$c->company_id,['period'=>$current,'journal_date'=>$targetDate,'source'=>'AUTO','event'=>'D11_PROSPECTIVE_ADJUSTMENT','source_document_type'=>'accounting_corrections','source_document_id'=>$c->id,'posting_key'=>$this->key($c,'ADJUSTMENT'),'description'=>'D-11 prospective adjustment for closed '.$j->doc_no],$this->mappedLines($c,abs($diff),$diff<0),$user);DB::table('accounting_corrections')->where('id',$c->id)->update(['status'=>'ADJUSTMENT_POSTED','adjustment_journal_id'=>$adjustment->id]);
   }else throw new RuntimeException('D-11 correction mode is invalid.');
   DB::table('accounting_corrections')->where('id',$c->id)->update(['status'=>'POSTED','posted_by'=>$user->id,'posted_at'=>now()]);$posted=$this->load($c->id);$this->audit->record('create',$posted,after:['decision'=>'BR-109','mode'=>$posted->correction_mode,'original_journal_id'=>$j->id,'reversal_journal_id'=>$reversal?->id,'corrected_journal_id'=>$repost?->id,'adjustment_journal_id'=>$adjustment?->id]);return['created'=>true,'result'=>'POSTED','correction'=>$posted];});
 }
 public function byJournal(Journal$journal,User$user):array{$j=Journal::withoutGlobalScopes()->whereKey($journal->id)->firstOrFail();$this->access($user,(int)$j->company_id);return['original_journal'=>$j,'corrections'=>AccountingCorrection::withoutGlobalScopes()->with('approvalRequest','reversalJournal','correctedJournal','adjustmentJournal')->where('company_id',$j->company_id)->where('original_journal_id',$j->id)->orderBy('correction_version')->get()];}
 public function detail(AccountingCorrection$c,User$user):array{$x=$this->load($c->id);$this->access($user,(int)$x->company_id);return$this->payload($x);}
 public function lineage(AccountingCorrection$c,User$user):array{$p=$this->detail($c,$user);$p['lineage']['policy']='BR-109_APPEND_ONLY';return$p;}
 private function authority(Journal$j):array{if($j->status!=='POSTED'||!$j->event||!$j->source_document_type||!$j->source_document_id||$j->lines->isEmpty())throw new RuntimeException('D-11 original authoritative journal/source is missing or not POSTED.');if($j->event!=='SHIPMENT_COGS'||$j->source_document_type!=='shipment_cogs')throw new RuntimeException('D-11 source has no supported authoritative costing/shipment accounting handoff.');$c=DB::table('shipment_cogs')->where('id',$j->source_document_id)->where('company_id',$j->company_id)->where('journal_id',$j->id)->where('status','POSTED')->first();if(!$c||abs((float)$c->base_cogs_total-(float)$j->total_debit)>.0001)throw new RuntimeException('D-11 D-10 source journal conflicts.');$lines=DB::table('shipment_cogs_lines')->where('shipment_cogs_id',$c->id)->where('company_id',$j->company_id)->orderBy('shipment_line_id')->get();if($lines->isEmpty())throw new RuntimeException('D-11 D-10/D-08 lineage is missing.');foreach($lines as$l)if(!DB::table('shipment_inventory_valuations')->where('id',$l->shipment_inventory_valuation_id)->where('company_id',$j->company_id)->where('shipment_id',$c->shipment_id)->exists())throw new RuntimeException('D-11 D-08 lineage is invalid.');return['currency'=>$c->currency,'shipment_cogs_id'=>$c->id,'shipment_id'=>$c->shipment_id,'d08_ids'=>$lines->pluck('shipment_inventory_valuation_id')->all(),'d10_source_hash'=>$c->source_hash];}
 private function mapping(Journal$j):AccountMapping{$m=AccountMapping::withoutGlobalScopes()->where('company_id',$j->company_id)->where('event',$j->event)->lockForUpdate()->first();if(!$m)throw new RuntimeException('D-11 authoritative account mapping is missing.');$accounts=DB::table('chart_of_accounts')->where('company_id',$j->company_id)->whereIn('id',[$m->debit_account_id,$m->credit_account_id])->where('is_active',true)->whereNull('deleted_at')->count();if($accounts!==2||(int)$m->debit_account_id===(int)$m->credit_account_id)throw new RuntimeException('D-11 account mapping is invalid or cross-company.');return$m;}
 private function period(int$c,string$p):object{$x=DB::table('gl_periods')->where('company_id',$c)->where('period',$p)->lockForUpdate()->first();if(!$x||!in_array($x->status,['OPEN','CLOSED'],true))throw new RuntimeException('D-11 original GL period authority is missing.');return$x;}
 private function currentOpenPeriod(int$c):array{$p=now()->format('Y-m');$d=now()->toDateString();$x=DB::table('gl_periods')->where('company_id',$c)->where('period',$p)->where('status','OPEN')->lockForUpdate()->first();if(!$x)throw new RuntimeException('D-11 current calendar GL period is not configured OPEN.');return[$p,$d];}
 private function hash(Journal$j,AccountMapping$m,array$a,float$corrected,float$difference,string$reason,int$version,string$state,string$mode,?string$targetPeriod,?string$targetDate):string{$lines=$j->lines->sortBy('id')->map(fn($l)=>['id'=>$l->id,'coa_id'=>$l->coa_id,'debit'=>(string)$l->debit,'credit'=>(string)$l->credit,'memo'=>$l->memo])->values()->all();return hash('sha256',json_encode(['company_id'=>$j->company_id,'original_journal'=>['id'=>$j->id,'event'=>$j->event,'source_type'=>$j->source_document_type,'source_id'=>$j->source_document_id,'period'=>$j->period,'date'=>$j->journal_date->toDateString(),'amount'=>(string)$j->total_debit,'posting_key'=>$j->posting_key,'lines'=>$lines],'authority'=>$a,'corrected'=>number_format($corrected,4,'.',''),'difference'=>number_format($difference,4,'.',''),'currency'=>$a['currency'],'period_state'=>$state,'mode'=>$mode,'target_period'=>$targetPeriod,'target_date'=>$targetDate,'mapping'=>['id'=>$m->id,'debit'=>$m->debit_account_id,'credit'=>$m->credit_account_id],'reason'=>$reason,'version'=>$version],JSON_THROW_ON_ERROR));}
 private function mappedLines(AccountingCorrection$c,float$amount,bool$reverse):array{$debit=$reverse?$c->credit_account_id:$c->debit_account_id;$credit=$reverse?$c->debit_account_id:$c->credit_account_id;return[['coa_id'=>$debit,'debit'=>$amount,'credit'=>0,'memo'=>'D-11 correction '.$c->id],['coa_id'=>$credit,'debit'=>0,'credit'=>$amount,'memo'=>'D-11 correction '.$c->id]];}
 private function key(AccountingCorrection$c,string$action):string{return hash('sha256','D11|'.$c->company_id.'|'.$c->original_journal_id.'|'.$c->correction_version.'|'.$action);}
 private function load(int$id):AccountingCorrection{return AccountingCorrection::withoutGlobalScopes()->with('approvalRequest.stepInstances','originalJournal.lines','reversalJournal.lines','correctedJournal.lines','adjustmentJournal.lines')->whereKey($id)->firstOrFail();}
 private function payload(AccountingCorrection$c):array{return['correction'=>$c,'lineage'=>['company_id'=>$c->company_id,'original_journal_id'=>$c->original_journal_id,'original_source_type'=>$c->original_source_type,'original_source_id'=>$c->original_source_id,'original_event'=>$c->original_event,'original_period'=>$c->original_gl_period,'original_posting_date'=>$c->original_posting_date->toDateString(),'original_amount'=>$c->original_amount,'currency'=>$c->currency,'reversal_journal_id'=>$c->reversal_journal_id,'corrected_journal_id'=>$c->corrected_journal_id,'adjustment_journal_id'=>$c->adjustment_journal_id,'source_hash'=>$c->source_hash]];}
 private function access(User$u,int$c):void{if((int)$u->company_id!==$c&&!$u->companies()->whereKey($c)->exists())throw new RuntimeException('User does not have access to the D-11 company.');}
}
