<?php

namespace Modules\Finance\Services;
use Carbon\Carbon;use Illuminate\Support\Facades\DB;use RuntimeException;
class FxExposureService
{
 public function snapshot(int$c,string$period,bool$lock=false):array{if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$period))throw new RuntimeException('Period wajib format YYYY-MM.');$asOf=Carbon::createFromFormat('Y-m-d',$period.'-01')->endOfMonth()->toDateString();$base=strtoupper((string)DB::table('companies')->where('id',$c)->value('base_currency'));$lines=[];
  $ar=DB::table('ar_invoices')->join('currencies','currencies.id','=','ar_invoices.currency_id')->where('ar_invoices.company_id',$c)->whereDate('ar_invoices.invoice_date','<=',$asOf)->where('ar_invoices.status','!=','VOID')->whereRaw('UPPER(currencies.code) <> ?',[$base])->select('ar_invoices.id','ar_invoices.currency_id','ar_invoices.total_amount','ar_invoices.exchange_rate');if($lock)$ar->lockForUpdate();foreach($ar->get()as$i){$paid=(float)DB::table('ar_payments')->where('ar_invoice_id',$i->id)->whereDate('payment_date','<=',$asOf)->sum('amount');$out=round((float)$i->total_amount-$paid,4);if($out>0.0001)$lines[]=$this->line('AR',$i,$out,$c,$asOf);}
  $ap=DB::table('supplier_invoices')->join('currencies','currencies.id','=','supplier_invoices.currency_id')->where('supplier_invoices.company_id',$c)->whereDate('supplier_invoices.invoice_date','<=',$asOf)->whereIn('supplier_invoices.status',['APPROVED','PAID'])->whereRaw('UPPER(currencies.code) <> ?',[$base])->select('supplier_invoices.id','supplier_invoices.currency_id','supplier_invoices.total_amount','supplier_invoices.exchange_rate');if($lock)$ap->lockForUpdate();foreach($ap->get()as$i){$paid=(float)DB::table('ap_payments')->where('supplier_invoice_id',$i->id)->whereDate('payment_date','<=',$asOf)->sum('amount');$out=round((float)$i->total_amount-$paid,4);if($out>0.0001)$lines[]=$this->line('AP',$i,$out,$c,$asOf);}
  usort($lines,fn($a,$b)=>[$a['side'],$a['document_id']]<=>[$b['side'],$b['document_id']]);$hash=hash('sha256',json_encode($lines,JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR));return['period'=>$period,'as_of_date'=>$asOf,'lines'=>$lines,'input_hash'=>$hash];}
 private function line(string$side,object$i,float$out,int$c,string$asOf):array{$carrying=(float)$i->exchange_rate;if($carrying<=0)throw new RuntimeException("{$side} invoice #{$i->id} tidak memiliki carrying rate valid.");$closing=app(FxRateService::class)->resolve($c,(int)$i->currency_id,$asOf);$old=round($out*$carrying,4);$new=round($out*$closing,4);$gain=$side==='AR'?round($new-$old,4):round($old-$new,4);return['side'=>$side,'document_id'=>(int)$i->id,'currency_id'=>(int)$i->currency_id,'foreign_outstanding'=>$out,'carrying_rate'=>$carrying,'closing_rate'=>$closing,'carrying_base'=>$old,'revalued_base'=>$new,'gain_loss'=>$gain];}
}
