<?php

namespace Modules\Finance\Services;
use Carbon\Carbon;use Illuminate\Support\Facades\DB;use Modules\Core\Models\User;use Modules\Core\Services\AuditService;use Modules\Finance\Models\FxRevaluationRun;use Modules\Finance\Models\GlPeriod;use RuntimeException;
class FxRevaluationService
{
 public function __construct(private FxExposureService$exposure,private GlPostingService$gl,private JournalService$journals,private AuditService$audit){}
 public function run(int$c,string$period,User$user):FxRevaluationRun{return DB::transaction(function()use($c,$period,$user){$this->access($user,$c);DB::table('companies')->where('id',$c)->lockForUpdate()->firstOrFail();$gl=GlPeriod::withoutGlobalScopes()->where('company_id',$c)->where('period',$period)->lockForUpdate()->first();if($gl&&$gl->status==='CLOSED')throw new RuntimeException("Periode {$period} sudah CLOSED.");$snap=$this->exposure->snapshot($c,$period,true);$existing=FxRevaluationRun::withoutGlobalScopes()->where('company_id',$c)->where('period',$period)->first();if($existing){if(!hash_equals($existing->input_hash,$snap['input_hash']))throw new RuntimeException('FX revaluation period ini sudah diposting dengan exposure/rate berbeda.');return$existing->load('lines','journals.journal');}$totals=['AR_FX_REVALUE_GAIN'=>0.0,'AR_FX_REVALUE_LOSS'=>0.0,'AP_FX_REVALUE_GAIN'=>0.0,'AP_FX_REVALUE_LOSS'=>0.0];foreach($snap['lines']as$l){if(abs($l['gain_loss'])<=0.0001)continue;$event=$l['side'].'_FX_REVALUE_'.($l['gain_loss']>0?'GAIN':'LOSS');$totals[$event]=round($totals[$event]+abs($l['gain_loss']),4);}$run=FxRevaluationRun::create(['company_id'=>$c,'period'=>$period,'as_of_date'=>$snap['as_of_date'],'status'=>'POSTED','input_hash'=>$snap['input_hash'],'totals'=>$totals,'posted_at'=>now(),'posted_by'=>$user->id]);foreach($snap['lines']as$l)$run->lines()->create($l);foreach($totals as$event=>$amount){if($amount<=0)continue;$result=$this->gl->postEvent($c,$event,'fx_revaluation_runs',$run->id,$amount,$period,$user,"FX revaluation {$period} {$event}",$snap['as_of_date']);$run->journals()->create(['event'=>$event,'journal_id'=>$result['journal']->id]);}$this->audit->record('create',$run,after:['period'=>$period,'line_count'=>count($snap['lines']),'totals'=>$totals]);return$run->load('lines','journals.journal');});}
 public function reverse(FxRevaluationRun$run,User$user):FxRevaluationRun{return DB::transaction(function()use($run,$user){$locked=FxRevaluationRun::withoutGlobalScopes()->with('journals.journal')->whereKey($run->id)->lockForUpdate()->firstOrFail();$this->access($user,(int)$locked->company_id);if($locked->status==='REVERSED')return$locked;$next=Carbon::createFromFormat('Y-m-d',$locked->period.'-01')->addMonth()->format('Y-m');foreach($locked->journals as$link){$rev=$this->journals->reverseIntoPeriod($link->journal,$next,$user,"Automatic FX reversal {$locked->period}");$link->update(['reversal_journal_id'=>$rev->id]);}$locked->update(['status'=>'REVERSED','reversed_at'=>now(),'reversed_by'=>$user->id]);$this->audit->record('reverse',$locked,after:['reversal_period'=>$next,'journal_count'=>$locked->journals->count()]);return$locked->fresh(['lines','journals.journal','journals.reversalJournal']);});}
 private function access(User$u,int$c):void{if((int)$u->company_id!==$c&&!$u->companies()->whereKey($c)->exists())throw new RuntimeException('User tidak memiliki akses ke company Finance.');}
}
