<?php

namespace Modules\Finance\Services;
use Carbon\Carbon;use Illuminate\Support\Facades\DB;use Modules\Core\Models\User;use Modules\Core\Services\AuditService;use Modules\Core\Services\NumberingService;use Modules\Finance\Models\FxRevaluationRun;use Modules\Finance\Models\GlPeriod;use Modules\Finance\Models\Journal;use RuntimeException;
class JournalService
{
 private const TOLERANCE=.0001;public function __construct(private NumberingService$numbering,private AuditService$audit,private FxExposureService$fxExposure){}
 public function post(int$c,array$meta,array$lines,User$user):Journal{$this->access($user,$c);$period=(string)($meta['period']??'');if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$period))throw new RuntimeException('Period wajib format YYYY-MM.');if(count($lines)<2)throw new RuntimeException('Jurnal wajib minimal 2 baris.');$date=Carbon::parse($meta['journal_date']??now()->toDateString());if($date->format('Y-m')!==$period)throw new RuntimeException('Journal date harus berada pada period jurnal.');$source=$meta['source']??'MANUAL';if(!in_array($source,Journal::SOURCES,true))throw new RuntimeException('Source jurnal tidak valid.');$d=0.;$cr=0.;$ids=[];foreach($lines as$i=>$l){$x=(float)($l['debit']??0);$y=(float)($l['credit']??0);if(($x>0&&$y>0)||($x<=0&&$y<=0))throw new RuntimeException("Baris {$i}: isi tepat satu sisi debit XOR credit.");$d+=$x;$cr+=$y;$ids[]=(int)($l['coa_id']??0);}if(abs($d-$cr)>self::TOLERANCE)throw new RuntimeException("BR-101: jurnal tidak balance — debit {$d} ≠ kredit {$cr}.");if(DB::table('chart_of_accounts')->where('company_id',$c)->whereIn('id',array_unique($ids))->count()!==count(array_unique($ids)))throw new RuntimeException('Seluruh COA jurnal wajib berasal dari company yang sama.');return DB::transaction(function()use($c,$meta,$lines,$d,$cr,$user,$period,$date,$source){$company=DB::table('companies')->where('id',$c)->whereNull('deleted_at')->lockForUpdate()->first();if(!$company||!(bool)$company->is_active)throw new RuntimeException('Company Finance tidak aktif.');$gl=$this->openPeriod($c,$period);$j=Journal::create(['company_id'=>$c,'doc_no'=>$this->numbering->next($c,'JE'),'period'=>$gl->period,'journal_date'=>$date->toDateString(),'source'=>$source,'event'=>$meta['event']??null,'source_document_type'=>$meta['source_document_type']??null,'source_document_id'=>$meta['source_document_id']??null,'posting_key'=>$meta['posting_key']??null,'description'=>$meta['description']??null,'total_debit'=>round($d,4),'total_credit'=>round($cr,4),'status'=>'POSTED','created_by'=>$user->id]);foreach($lines as$l)$j->lines()->create(['coa_id'=>$l['coa_id'],'debit'=>(float)($l['debit']??0),'credit'=>(float)($l['credit']??0),'memo'=>$l['memo']??null]);$this->audit->record('create',$j,after:['doc_no'=>$j->doc_no,'total'=>$j->total_debit,'event'=>$j->event]);return$j->load('lines');});}
 public function reverse(Journal$j,User$u,?string$r=null):Journal{return$this->reverseIntoPeriod($j,$j->period,$u,$r,Carbon::createFromFormat('Y-m-d',$j->period.'-01')->endOfMonth()->toDateString());}
 public function reverseIntoPeriod(Journal$j,string$period,User$u,?string$reason=null,?string$date=null):Journal{return DB::transaction(function()use($j,$period,$u,$reason,$date){$x=Journal::withoutGlobalScopes()->with('lines')->whereKey($j->id)->lockForUpdate()->firstOrFail();$this->access($u,(int)$x->company_id);if($x->status==='VOID'||Journal::withoutGlobalScopes()->where('reverses_journal_id',$x->id)->exists())throw new RuntimeException('Jurnal sudah direverse.');$lines=$x->lines->map(fn($l)=>['coa_id'=>$l->coa_id,'debit'=>(float)$l->credit,'credit'=>(float)$l->debit,'memo'=>'Reversal '.$x->doc_no])->all();$rev=$this->post($x->company_id,['period'=>$period,'journal_date'=>$date??$period.'-01','source'=>$x->source,'event'=>'REVERSAL','source_document_type'=>'journals','source_document_id'=>$x->id,'description'=>'REVERSAL '.$x->doc_no.($reason?': '.$reason:'')],$lines,$u);$rev->update(['reverses_journal_id'=>$x->id]);$x->update(['status'=>'VOID']);$this->audit->record('reverse',$x,after:['reversal'=>$rev->doc_no,'reversal_period'=>$period]);return$rev;});}
 private function openPeriod(int$c,string$p):GlPeriod{$g=GlPeriod::withoutGlobalScopes()->where('company_id',$c)->where('period',$p)->lockForUpdate()->first();if(!$g)$g=GlPeriod::create(['company_id'=>$c,'period'=>$p,'status'=>'OPEN']);if($g->status==='CLOSED')throw new RuntimeException("BR-103: periode {$p} sudah CLOSED.");return$g;}
 public function closePeriod(int$c,string$p,User$u):GlPeriod{$this->access($u,$c);if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$p))throw new RuntimeException('Period wajib format YYYY-MM.');return DB::transaction(function()use($c,$p,$u){$company=DB::table('companies')->where('id',$c)->whereNull('deleted_at')->lockForUpdate()->first();if(!$company||!(bool)$company->is_active)throw new RuntimeException('Company Finance tidak aktif.');$g=GlPeriod::withoutGlobalScopes()->where('company_id',$c)->where('period',$p)->lockForUpdate()->firstOrFail();if($g->status==='CLOSED')return$g;$snap=$this->fxExposure->snapshot($c,$p,false);if($snap['lines']!==[]){$run=FxRevaluationRun::withoutGlobalScopes()->where('company_id',$c)->where('period',$p)->first();if(!$run)throw new RuntimeException("Periode {$p} memiliki exposure FX dan belum direvaluasi.");if(!hash_equals($run->input_hash,$snap['input_hash']))throw new RuntimeException('Exposure/rate FX berubah setelah revaluation; period tidak dapat ditutup.');}$g->update(['status'=>'CLOSED','closed_by'=>$u->id,'closed_at'=>now()]);$this->audit->record('close','gl_periods',documentId:$g->id,after:['period'=>$p,'fx_revaluation_verified'=>true]);return$g->fresh();});}
 public function trialBalance(int$c,string$p):array{if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$p))throw new RuntimeException('Period wajib format YYYY-MM.');return DB::table('journal_lines')->join('journals','journals.id','=','journal_lines.journal_id')->join('chart_of_accounts','chart_of_accounts.id','=','journal_lines.coa_id')->where('journals.company_id',$c)->where('journals.period',$p)->selectRaw('chart_of_accounts.code,chart_of_accounts.name,chart_of_accounts.type,chart_of_accounts.normal_balance,SUM(journal_lines.debit) total_debit,SUM(journal_lines.credit) total_credit')->groupBy('chart_of_accounts.id','chart_of_accounts.code','chart_of_accounts.name','chart_of_accounts.type','chart_of_accounts.normal_balance')->orderBy('chart_of_accounts.code')->get()->all();}private function access(User$u,int$c):void{if((int)$u->company_id!==$c&&!$u->companies()->whereKey($c)->exists())throw new RuntimeException('User tidak memiliki akses ke company Finance.');}
}
