<?php
namespace Modules\Finance\Services;
use Carbon\Carbon;use Illuminate\Support\Facades\DB;use Modules\Core\Models\User;use Modules\Core\Services\AuditService;use Modules\Finance\Models\FxRevaluationRun;use Modules\Finance\Models\GlPeriod;use Modules\Finance\Models\PeriodCloseRun;use RuntimeException;
class PeriodCloseService
{
 public function __construct(private FxExposureService$fx,private JournalService$journals,private AuditService$audit){}
 public function prepare(int$c,string$p,array$a,User$u):PeriodCloseRun{return DB::transaction(function()use($c,$p,$a,$u){$this->access($u,$c);$this->period($p);DB::table('companies')->where('id',$c)->lockForUpdate()->firstOrFail();GlPeriod::withoutGlobalScopes()->firstOrCreate(['company_id'=>$c,'period'=>$p],['status'=>'OPEN']);$gl=GlPeriod::withoutGlobalScopes()->where('company_id',$c)->where('period',$p)->lockForUpdate()->firstOrFail();if($gl->status==='CLOSED')throw new RuntimeException('Periode sudah CLOSED.');$att=['backup_verified'=>(bool)($a['backup_verified']??false),'tax_reviewed'=>(bool)($a['tax_reviewed']??false),'notes'=>trim((string)($a['notes']??''))];$snap=$this->snapshot($c,$p,$att);$hash=$this->hash($snap,$att);$run=PeriodCloseRun::withoutGlobalScopes()->where('company_id',$c)->where('period',$p)->lockForUpdate()->first();if($run&&in_array($run->status,['APPROVED','CLOSED'],true))throw new RuntimeException('Period-close run sudah disetujui atau ditutup.');$payload=['status'=>$this->passed($snap)?'READY':'DRAFT','checklist_snapshot'=>$snap,'attestations'=>$att,'snapshot_hash'=>$hash,'prepared_by'=>$u->id,'prepared_at'=>now(),'approved_by'=>null,'approved_at'=>null];if($run)$run->update($payload);else$run=PeriodCloseRun::create($payload+['company_id'=>$c,'period'=>$p]);$this->audit->record('update',$run,after:['period'=>$p,'status'=>$run->status,'snapshot_hash'=>$hash]);return$run->fresh();});}
 public function approve(PeriodCloseRun$r,User$u):PeriodCloseRun{return DB::transaction(function()use($r,$u){$x=$this->locked($r,$u);if($x->status!=='READY')throw new RuntimeException('Checklist belum READY.');if((int)$x->prepared_by===(int)$u->id)throw new RuntimeException('Maker dan approver period close harus berbeda.');$snap=$this->snapshot((int)$x->company_id,$x->period,$x->attestations);if(!$this->passed($snap)||!hash_equals($x->snapshot_hash,$this->hash($snap,$x->attestations)))throw new RuntimeException('Checklist berubah atau tidak lagi valid; prepare ulang.');$x->update(['status'=>'APPROVED','approved_by'=>$u->id,'approved_at'=>now()]);$this->audit->record('approve',$x,after:['period'=>$x->period,'snapshot_hash'=>$x->snapshot_hash]);return$x->fresh();});}
 public function close(PeriodCloseRun$r,User$u):PeriodCloseRun{return DB::transaction(function()use($r,$u){$x=$this->locked($r,$u);if($x->status==='CLOSED')return$x;if($x->status!=='APPROVED')throw new RuntimeException('Period close belum APPROVED.');$snap=$this->snapshot((int)$x->company_id,$x->period,$x->attestations);if(!$this->passed($snap)||!hash_equals($x->snapshot_hash,$this->hash($snap,$x->attestations)))throw new RuntimeException('Checklist berubah setelah approval; close dibatalkan.');$this->journals->closePeriod((int)$x->company_id,$x->period,$u);$x->update(['status'=>'CLOSED','closed_by'=>$u->id,'closed_at'=>now()]);$this->audit->record('close',$x,after:['period'=>$x->period,'approved_by'=>$x->approved_by]);return$x->fresh();});}
 private function locked(PeriodCloseRun$r,User$u):PeriodCloseRun{$c=(int)$r->company_id;$this->access($u,$c);DB::table('companies')->where('id',$c)->lockForUpdate()->firstOrFail();GlPeriod::withoutGlobalScopes()->where('company_id',$c)->where('period',$r->period)->lockForUpdate()->firstOrFail();return PeriodCloseRun::withoutGlobalScopes()->where('company_id',$c)->whereKey($r->id)->lockForUpdate()->firstOrFail();}
 private function snapshot(int$c,string$p,array$a):array{$start=$p.'-01';$end=Carbon::createFromFormat('Y-m-d',$start)->endOfMonth()->toDateString();$tot=DB::table('journals')->where('company_id',$c)->where('period',$p)->selectRaw('COALESCE(SUM(total_debit),0) d,COALESCE(SUM(total_credit),0) c')->first();$diff=round((float)$tot->d-(float)$tot->c,4);$pending=DB::table('supplier_invoices')->where('company_id',$c)->whereDate('invoice_date','<=',$end)->where(function($q){$q->whereIn('status',['DRAFT','SUBMITTED'])->orWhere(function($x){$x->where('status','APPROVED')->where('match_status','!=','MATCHED');});})->count();$accounts=DB::table('bank_accounts')->where('company_id',$c)->where('is_active',true)->pluck('id');$missing=[];foreach($accounts as$id)if(!DB::table('bank_statement_imports')->where('company_id',$c)->where('bank_account_id',$id)->where('status','RECONCILED')->whereDate('period_start','<=',$start)->whereDate('period_end','>=',$end)->exists())$missing[]=(int)$id;$openBank=DB::table('bank_statement_imports')->where('company_id',$c)->where('status','IMPORTED')->whereDate('period_start','<=',$end)->whereDate('period_end','>=',$start)->count();$fx=$this->fx->snapshot($c,$p,false);$fxRun=$fx['lines']===[]?null:FxRevaluationRun::withoutGlobalScopes()->where('company_id',$c)->where('period',$p)->first();$fxOk=$fx['lines']===[]||($fxRun&&hash_equals($fxRun->input_hash,$fx['input_hash']));$prior=Carbon::createFromFormat('Y-m-d',$start)->subMonth()->format('Y-m');$priorRun=FxRevaluationRun::withoutGlobalScopes()->where('company_id',$c)->where('period',$prior)->first();$priorOk=!$priorRun||$priorRun->status==='REVERSED'||$priorRun->journals()->count()===0;return['journal_balance'=>['passed'=>abs($diff)<=.0001,'difference'=>$diff],'pending_ap'=>['passed'=>$pending===0,'count'=>$pending],'bank_reconciliation'=>['passed'=>$missing===[]&&$openBank===0,'missing_account_ids'=>$missing,'open_imports'=>$openBank],'fx_revaluation'=>['passed'=>(bool)$fxOk,'exposure_count'=>count($fx['lines']),'input_hash'=>$fx['input_hash']],'prior_fx_reversal'=>['passed'=>$priorOk,'prior_period'=>$prior,'status'=>$priorRun?->status],'backup_verified'=>['passed'=>$a['backup_verified']===true],'tax_reviewed'=>['passed'=>$a['tax_reviewed']===true]];}
 private function passed(array$s):bool{foreach($s as$x)if(!$x['passed'])return false;return true;}private function hash(array$s,array$a):string{return hash('sha256',json_encode(['checks'=>$s,'attestations'=>$a],JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR));}private function period(string$p):void{if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$p))throw new RuntimeException('Period wajib format YYYY-MM.');}private function access(User$u,int$c):void{if((int)$u->company_id!==$c&&!$u->companies()->whereKey($c)->exists())throw new RuntimeException('User tidak memiliki akses ke company Finance.');}
}
