<?php

namespace Modules\Finance\Services;

use Illuminate\Support\Collection;use Illuminate\Support\Facades\DB;use Modules\Core\Models\User;use Modules\Core\Services\AuditService;use Modules\Finance\Models\AccountMapping;use Modules\Finance\Models\Journal;use Modules\Finance\Models\ShipmentCogs;use Modules\Finance\Models\ShipmentCogsLine;use Modules\Shipping\Models\Shipment;use Modules\Shipping\Models\ShipmentInventoryValuation;use RuntimeException;

class ShipmentCogsService
{
 public const EVENT='SHIPMENT_COGS';
 public function __construct(private JournalService$journals,private AuditService$audit){}
 public function post(Shipment$shipment,User$user):array
 {
  return DB::transaction(function()use($shipment,$user):array{
   $s=Shipment::withoutGlobalScopes()->with('lines','packingList.productionOrder')->whereKey($shipment->id)->lockForUpdate()->firstOrFail();$this->access($user,(int)$s->company_id);
   if($s->status!=='SHIPPED')throw new RuntimeException('D-10 requires a SHIPPED Shipment.');if(!$s->ship_date)throw new RuntimeException('D-10 Shipment posting date is missing.');if(!$s->packingList?->production_order_id)throw new RuntimeException('D-10 MO/Packing lineage is missing.');
   $company=DB::table('companies')->where('id',$s->company_id)->whereNull('deleted_at')->lockForUpdate()->first();if(!$company||!(bool)$company->is_active)throw new RuntimeException('D-10 company is not active.');
   $mapping=AccountMapping::withoutGlobalScopes()->where('company_id',$s->company_id)->where('event',self::EVENT)->lockForUpdate()->first();if(!$mapping)throw new RuntimeException('D-10 SHIPMENT_COGS account mapping is missing.');
   $accounts=DB::table('chart_of_accounts')->where('company_id',$s->company_id)->whereIn('id',[$mapping->debit_account_id,$mapping->credit_account_id])->where('is_active',true)->whereNull('deleted_at')->get();
   if($accounts->count()!==2||(int)$mapping->debit_account_id===(int)$mapping->credit_account_id)throw new RuntimeException('D-10 SHIPMENT_COGS account mapping is invalid or cross-company.');
   $d08=ShipmentInventoryValuation::withoutGlobalScopes()->where('company_id',$s->company_id)->where('shipment_id',$s->id)->orderBy('shipment_line_id')->lockForUpdate()->get();
   if($d08->count()!==$s->lines->count()||$d08->isEmpty())throw new RuntimeException('D-10 requires complete immutable D-08 valuation for every Shipment Line.');
   $sources=$this->validateD08($s,$d08);$currency=$sources->pluck('currency')->unique()->values();if($currency->count()!==1||$currency->first()!==$company->base_currency)throw new RuntimeException('D-10 currency is missing, mixed, or requires undefined FX conversion.');
   $date=$s->ship_date->toDateString();$period=$s->ship_date->format('Y-m');$this->openPeriod((int)$s->company_id,$period);
   $lineInputs=$sources->map(fn(array$x)=>['d08_id'=>$x['d08']->id,'shipment_line_id'=>$x['d08']->shipment_line_id,'quantity'=>(string)$x['d08']->shipment_quantity,'unit_cost'=>(string)$x['d08']->moving_average_unit_cost,'base_cogs'=>(string)$x['d08']->shipment_inventory_cost,'currency'=>$x['d08']->currency,'d08_version'=>(int)$x['d08']->valuation_version,'d08_source_hash'=>$x['d08']->source_hash,'shipment_movement_id'=>(int)$x['d08']->shipment_movement_id,'shipment_ledger_id'=>(int)$x['d08']->shipment_ledger_id,'production_receipt_movement_id'=>(int)$x['d08']->production_receipt_movement_id])->values();
   $source=['company_id'=>(int)$s->company_id,'shipment_id'=>(int)$s->id,'event'=>self::EVENT,'posting_date'=>$date,'period'=>$period,'currency'=>$currency->first(),'mapping'=>['id'=>$mapping->id,'debit'=>$mapping->debit_account_id,'credit'=>$mapping->credit_account_id],'lines'=>$lineInputs->all()];
   $hash=hash('sha256',json_encode($source,JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR));$postingKey=hash('sha256','D10|'.$s->company_id.'|'.$s->id.'|'.self::EVENT);$total=round((float)$sources->sum(fn(array$x)=>(float)$x['d08']->shipment_inventory_cost),4);
   $existing=ShipmentCogs::withoutGlobalScopes()->with('lines','journal.lines')->where('company_id',$s->company_id)->where('shipment_id',$s->id)->where('event',self::EVENT)->lockForUpdate()->first();
   if($existing){$this->assertReplay($existing,$hash,$postingKey,$total,$date,$period,$currency->first(),$lineInputs);return['created'=>false,'cogs'=>$existing];}
   $id=DB::table('shipment_cogs')->insertGetId(['company_id'=>$s->company_id,'shipment_id'=>$s->id,'account_mapping_id'=>$mapping->id,'debit_account_id'=>$mapping->debit_account_id,'credit_account_id'=>$mapping->credit_account_id,'journal_id'=>null,'event'=>self::EVENT,'base_cogs_total'=>$total,'currency'=>$currency->first(),'posting_date'=>$date,'gl_period'=>$period,'status'=>'PENDING','posting_key'=>$postingKey,'source_hash'=>$hash,'created_by'=>$user->id,'created_at'=>now()]);
   foreach($sources as$x){$v=$x['d08'];$lineHash=hash('sha256',json_encode(['cogs_source'=>$hash,'d08_id'=>$v->id,'shipment_line_id'=>$v->shipment_line_id,'amount'=>(string)$v->shipment_inventory_cost,'d08_hash'=>$v->source_hash],JSON_THROW_ON_ERROR));ShipmentCogsLine::create(['shipment_cogs_id'=>$id,'company_id'=>$s->company_id,'shipment_line_id'=>$v->shipment_line_id,'shipment_inventory_valuation_id'=>$v->id,'shipment_movement_id'=>$v->shipment_movement_id,'shipment_ledger_id'=>$v->shipment_ledger_id,'production_receipt_movement_id'=>$v->production_receipt_movement_id,'quantity'=>$v->shipment_quantity,'unit_cost'=>$v->moving_average_unit_cost,'base_cogs'=>$v->shipment_inventory_cost,'currency'=>$v->currency,'d08_valuation_version'=>$v->valuation_version,'d08_source_hash'=>$v->source_hash,'source_hash'=>$lineHash,'created_at'=>now()]);}
   $journal=null;$status='ZERO_COST';if($total>0){$journalLines=[];foreach($sources as$x){$v=$x['d08'];$amount=(float)$v->shipment_inventory_cost;if($amount<=0)continue;$memo='D-10 Shipment Line '.$v->shipment_line_id.' / D-08 '.$v->id;$journalLines[]=['coa_id'=>$mapping->debit_account_id,'debit'=>$amount,'credit'=>0,'memo'=>$memo];$journalLines[]=['coa_id'=>$mapping->credit_account_id,'debit'=>0,'credit'=>$amount,'memo'=>$memo];}
    $journal=$this->journals->post((int)$s->company_id,['period'=>$period,'journal_date'=>$date,'source'=>'AUTO','event'=>self::EVENT,'source_document_type'=>'shipment_cogs','source_document_id'=>$id,'posting_key'=>$postingKey,'description'=>'Base COGS Shipment '.$s->doc_no],$journalLines,$user);$status='POSTED';}
   DB::table('shipment_cogs')->where('id',$id)->where('company_id',$s->company_id)->where('status','PENDING')->update(['journal_id'=>$journal?->id,'status'=>$status]);$cogs=ShipmentCogs::withoutGlobalScopes()->with('lines','journal.lines')->whereKey($id)->firstOrFail();$this->audit->record('create',$cogs,after:['event'=>self::EVENT,'shipment_id'=>$s->id,'journal_id'=>$journal?->id,'source_hash'=>$hash,'status'=>$status]);return['created'=>true,'cogs'=>$cogs];
  });
 }
 public function forShipment(Shipment$shipment,User$user):array{$s=Shipment::withoutGlobalScopes()->whereKey($shipment->id)->firstOrFail();$this->access($user,(int)$s->company_id);$c=ShipmentCogs::withoutGlobalScopes()->with('lines','journal.lines')->where('company_id',$s->company_id)->where('shipment_id',$s->id)->where('event',self::EVENT)->first();return$c?$this->payload($c):['status'=>'NOT_POSTED','shipment'=>['id'=>$s->id,'doc_no'=>$s->doc_no,'status'=>$s->status]];}
 public function detail(ShipmentCogs$cogs,User$user):array{$c=ShipmentCogs::withoutGlobalScopes()->with('shipment.packingList.productionOrder','lines.d08','journal.lines')->whereKey($cogs->id)->firstOrFail();$this->access($user,(int)$c->company_id);return$this->payload($c);}
 public function lineage(ShipmentCogs$cogs,User$user):array{$p=$this->detail($cogs,$user);$p['correction']=['status'=>'DEFERRED_TO_D11','original_mutation_allowed'=>false];return$p;}
 private function validateD08(Shipment$s,Collection$rows):Collection
 {
  return$rows->map(function($v)use($s):array{$line=$s->lines->firstWhere('id',$v->shipment_line_id);if(!$line||(int)$v->company_id!==(int)$s->company_id||(int)$v->packing_list_id!==(int)$s->packing_list_id||(int)$v->production_order_id!==(int)$s->packingList->production_order_id||$v->item_type!=='FG'||$v->ownership!=='COMPANY'||$v->valuation_event!=='ITS_SHIPMENT_OUT'||$v->cost_method!=='MOVING_AVERAGE'||(int)$v->valuation_version<1||!preg_match('/^[a-f0-9]{64}$/',$v->source_hash??''))throw new RuntimeException('D-10 D-08 identity or lineage is invalid.');
   if((int)$v->style_id!==(int)$line->style_id||(int)$v->colorway_id!==(int)$line->colorway_id||(int)$v->size_id!==(int)$line->size_id||abs((float)$v->shipment_quantity-(float)$line->qty_shipped)>.0001||(float)$v->moving_average_unit_cost<0||(float)$v->shipment_inventory_cost<0)throw new RuntimeException('D-10 D-08 Shipment Line evidence conflicts.');
   $move=DB::table('stock_movements')->where('id',$v->shipment_movement_id)->where('company_id',$s->company_id)->where('movement_type','SHIPMENT')->where('source_document_type','shipments')->where('source_document_id',$s->id)->first();$ledger=DB::table('stock_ledger')->where('id',$v->shipment_ledger_id)->where('company_id',$s->company_id)->where('movement_type','SHIPMENT')->where('source_document_type','shipments')->where('source_document_id',$s->id)->where('source_document_line_id',$line->id)->where('ownership','COMPANY')->where('item_type','FG')->first();$receipt=DB::table('stock_movements')->where('id',$v->production_receipt_movement_id)->where('company_id',$s->company_id)->where('movement_type','PRODUCTION_RECEIPT')->where('source_document_type','packing_lists')->where('source_document_id',$s->packing_list_id)->first();$mo=DB::table('production_orders')->where('id',$v->production_order_id)->where('company_id',$s->company_id)->first();
   if(!$move||!$ledger||!$receipt||!$mo||$ledger->unit_cost===null||$ledger->total_cost===null||abs((float)$ledger->unit_cost-(float)$v->moving_average_unit_cost)>.000001||abs((float)$ledger->total_cost-(float)$v->shipment_inventory_cost)>.0001)throw new RuntimeException('D-10 valued ITS Shipment or Production Receipt evidence conflicts.');return['d08'=>$v,'currency'=>$v->currency];});
 }
 private function openPeriod(int$company,string$period):void{DB::table('gl_periods')->insertOrIgnore(['company_id'=>$company,'period'=>$period,'status'=>'OPEN','created_at'=>now(),'updated_at'=>now()]);$gl=DB::table('gl_periods')->where('company_id',$company)->where('period',$period)->lockForUpdate()->first();if(!$gl||$gl->status==='CLOSED')throw new RuntimeException("BR-103: periode {$period} sudah CLOSED.");}
 private function assertReplay(ShipmentCogs$c,string$hash,string$key,float$total,string$date,string$period,string$currency,Collection$lines):void{if(!hash_equals($c->source_hash,$hash)||!hash_equals($c->posting_key,$key)||abs((float)$c->base_cogs_total-$total)>.0001||$c->posting_date->toDateString()!==$date||$c->gl_period!==$period||$c->currency!==$currency||$c->lines->count()!==$lines->count())throw new RuntimeException('D-10 IDEMPOTENCY CONFLICT: immutable COGS source changed.');if($c->status==='POSTED'&&(!$c->journal||$c->journal->status!=='POSTED'||$c->journal->event!==self::EVENT||$c->journal->posting_key!==$key))throw new RuntimeException('D-10 journal identity conflicts.');if(!in_array($c->status,['POSTED','ZERO_COST'],true))throw new RuntimeException('D-10 COGS is incomplete.');}
 private function payload(ShipmentCogs$c):array{return['status'=>$c->status,'cogs'=>$c,'base_cogs_source'=>'IMMUTABLE_D08_SHIPMENT_INVENTORY_COST','journal'=>$c->journal,'d11_handoff'=>['original_journal_id'=>$c->journal_id,'shipment_id'=>$c->shipment_id,'d08_valuation_ids'=>$c->lines->pluck('shipment_inventory_valuation_id'),'posting_date'=>$c->posting_date->toDateString(),'gl_period'=>$c->gl_period,'currency'=>$c->currency,'posting_key'=>$c->posting_key,'source_hash'=>$c->source_hash,'correction'=>'DEFERRED_TO_D11']];}
 private function access(User$u,int$c):void{if((int)$u->company_id!==$c&&!$u->companies()->whereKey($c)->exists())throw new RuntimeException('User does not have access to the D-10 company.');}
}
