<?php
namespace Modules\Shipping\Services;
use Illuminate\Support\Facades\DB;use Modules\Core\Models\User;use Modules\Sales\Models\SalesOrder;use Modules\Shipping\Models\Shipment;use RuntimeException;
class CommercialFulfillmentService
{
 public function authorityMatrix(int$c,User$u):array{$this->access($u,$c);return['rows'=>[['boundary'=>'Delivery Schedule → Shipment','authority'=>'Persisted allocation to earliest OPEN schedule with sufficient remaining quantity','status'=>'DEFINED'],['boundary'=>'Packing/Shipment quantity','authority'=>'Packing List Carton matrix and Shipment lines','status'=>'DEFINED'],['boundary'=>'Container','authority'=>'Shipment-scoped container number, size and seal evidence','status'=>'DEFINED'],['boundary'=>'Commercial Invoice','authority'=>'Shipment matrix × immutable Sales Order price; currency/rate snapshot from SO','status'=>'DEFINED'],['boundary'=>'Export documents','authority'=>'Shipment-scoped COO/Bill of Lading/LC/Customs/Other references','status'=>'DEFINED'],['boundary'=>'Commercial Invoice → AR','authority'=>'AR creation requires ISSUED Commercial Invoice for new transactions','status'=>'DEFINED'],['boundary'=>'Export completeness checklist','authority'=>'Mandatory document set per destination/LC is not defined','status'=>'PARTIAL']], 'states'=>['DELIVERY_SCHEDULE_LINK'=>'DEFINED','COMMERCIAL_INVOICE'=>'DEFINED','EXPORT_DOCUMENT_AUTHORITY'=>'DEFINED','COMMERCIAL_INVOICE_AR_GATE'=>'DEFINED','MANDATORY_EXPORT_DOCUMENT_SET'=>'NOT DEFINED'],'writes_performed'=>false,'migration'=>'2026_09_04_000043'];}
 public function salesOrder(SalesOrder$s,User$u):array{$so=SalesOrder::withoutGlobalScopes()->with(['customer','lines'])->whereKey($s->id)->firstOrFail();$this->access($u,(int)$so->company_id);return['sales_order'=>['id'=>$so->id,'doc_no'=>$so->doc_no,'buyer'=>$so->customer?->name,'ordered_qty'=>(float)$so->lines->sum('qty')],'shipments'=>Shipment::withoutGlobalScopes()->with(['deliverySchedule','commercialInvoice.currency','containers','exportDocuments'])->where('company_id',$so->company_id)->where('sales_order_id',$so->id)->orderBy('id')->get()];}
 public function shipment(Shipment$s,User$u):array{$ship=Shipment::withoutGlobalScopes()->with(['salesOrder.customer','packingList','deliverySchedule','lines','containers','commercialInvoice.currency','commercialInvoice.lines','commercialInvoice.arInvoice','exportDocuments'])->whereKey($s->id)->firstOrFail();$this->access($u,(int)$ship->company_id);$movement=DB::table('stock_movements')->where('company_id',$ship->company_id)->where('movement_type','SHIPMENT')->where('source_document_type','shipments')->where('source_document_id',$ship->id)->first();return['shipment'=>$ship,'its_shipment'=>$movement?(array)$movement:['status'=>'NOT_POSTED'],'lineage'=>'SO → Delivery Schedule → Packing List/Carton Matrix → Shipment → Container + Commercial Invoice + Export Documents → AR Invoice','commercial_authority'=>'SHIPMENT_MATRIX_X_SO_PRICE','mandatory_export_document_set'=>'NOT DEFINED'];}
 private function access(User$u,int$c):void{if((int)$u->company_id!==$c&&!$u->companies()->whereKey($c)->exists())throw new RuntimeException('User tidak memiliki akses ke company fulfillment.');}
}
