"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Button, Input, StatusBadge } from "@/components/ui";

type Status = "DEFINED" | "PARTIAL" | "NOT DEFINED" | "DERIVED" | "LEGACY";
interface Authority { rows: { boundary: string; authority: string; status: Status }[]; quantity_candidates: { candidate: string; existing_authority: string; used_by: string; status: Status }[]; states: Record<string,string>; migration: string; writes_performed: boolean }
interface SoView { sales_order: { id:number; doc_no:string; status:string; buyer:string; ordered_qty:number; tolerance_pct:number; tolerance_source:string }; matrix: { line_id:number; style:string; color:string; size:string; ordered_qty:number; shipped_qty:number; remaining_to_order_qty:number; commercial_ceiling_qty:number; remaining_to_ceiling_qty:number }[]; delivery_schedules: { status:string; shipment_link:string; rows:{id:number;delivery_date:string;qty:string;destination:string|null}[]; scheduled_qty:number; remaining_qty:null; reason:string }; packing_lists:{id:number;doc_no:string;status:string;qty:string}[]; shipments:{id:number;doc_no:string;ship_date:string;status:string;tolerance_check:string}[]; partial_shipment:{status:string;defined:string;undefined:string} }
interface ShipmentView { shipment:{doc_no:string;status:string;ship_date:string;qty:number;tolerance_check:string;over_tolerance_approved:boolean}; sales_order_fulfillment:SoView; packing_source:{doc_no:string;status:string;authority:string;production_receipt_id:number|null}; its_shipment:{doc_no?:string;status:string}; delivery_schedule_link:{status:string;reason:string}; commercial_documents:{commercial_invoice:string;export_documents:string;ar_invoice:{doc_no:string;status:string;classification:string}|null}; valuation:{shipment:string;cogs:string;cogs_journal_allowed:boolean}; lineage:{forward:string;reverse:string} }

export function CommercialFulfillmentPanel() {
  const [authority,setAuthority]=useState<Authority|null>(null);
  const [soId,setSoId]=useState(""); const [shipmentId,setShipmentId]=useState("");
  const [so,setSo]=useState<SoView|null>(null); const [shipment,setShipment]=useState<ShipmentView|null>(null);
  const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  useEffect(()=>{api.get<Authority>("/shipping/commercial-fulfillment/authority").then(setAuthority).catch(e=>setError(e.message));},[]);
  const fmt=(v:number|string)=>Number(v).toLocaleString("id-ID",{maximumFractionDigits:4});
  async function loadSo(){if(!soId)return;setBusy(true);setError(null);try{setSo(await api.get<SoView>(`/shipping/commercial-fulfillment/sales-orders/${soId}`));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function loadShipment(){if(!shipmentId)return;setBusy(true);setError(null);try{setShipment(await api.get<ShipmentView>(`/shipping/shipments/${shipmentId}/commercial-lineage`));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  if(!authority)return <section className="rounded-xl border bg-white p-4 text-sm text-slate-500">Memuat commercial fulfillment authority…</section>;
  return <section className="space-y-4 rounded-xl border bg-white p-4">
    <div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">Commercial Fulfillment Authority</h2><p className="mt-1 text-sm text-slate-700">SO → SO Matrix → Delivery Schedule? → Packing/FG → Shipment</p></div><div className="text-right text-xs text-slate-500"><p>Read-only · Migration {authority.migration}</p><p>Writes {authority.writes_performed?"YES":"NONE"}</p></div></div>
    {error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="grid gap-2 sm:grid-cols-3"><div className="rounded bg-slate-100 p-3 text-xs"><p className="text-slate-500">Delivery Schedule → Shipment</p><b>⚪ {authority.states.DELIVERY_SCHEDULE_LINK}</b></div><div className="rounded bg-slate-100 p-3 text-xs"><p className="text-slate-500">Commercial Invoice / Export Docs</p><b>⚪ NOT DEFINED</b></div><div className="rounded bg-slate-100 p-3 text-xs"><p className="text-slate-500">Shipment valuation / COGS</p><b>⚪ NOT DEFINED</b></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b text-left text-xs text-slate-500"><tr><th className="py-2">Boundary</th><th>Authority</th><th>Status</th></tr></thead><tbody>{authority.rows.map(row=><tr key={row.boundary} className="border-b align-top last:border-0"><td className="py-2 pr-3 font-medium">{row.boundary}</td><td className="py-2 pr-3 text-xs text-slate-600">{row.authority}</td><td className="py-2"><StatusBadge status={row.status}/></td></tr>)}</tbody></table></div>
    <div className="grid gap-3 lg:grid-cols-2"><div className="rounded-lg border p-3"><p className="mb-2 font-medium">SO fulfillment lookup</p><div className="flex gap-2"><Input type="number" min="1" placeholder="Sales Order ID" value={soId} onChange={e=>setSoId(e.target.value)}/><Button onClick={loadSo} disabled={!soId} loading={busy}>Muat</Button></div></div><div className="rounded-lg border p-3"><p className="mb-2 font-medium">Shipment commercial lineage</p><div className="flex gap-2"><Input type="number" min="1" placeholder="Shipment ID" value={shipmentId} onChange={e=>setShipmentId(e.target.value)}/><Button onClick={loadShipment} disabled={!shipmentId} loading={busy}>Muat</Button></div></div></div>
    {so&&<div className="space-y-3 rounded-lg border border-blue-200 bg-blue-50 p-3"><div className="flex flex-wrap justify-between"><div><b className="font-mono">{so.sales_order.doc_no}</b><p className="text-xs">{so.sales_order.buyer} · {so.sales_order.status}</p></div><p className="text-sm">Ordered {fmt(so.sales_order.ordered_qty)} · tolerance {fmt(so.sales_order.tolerance_pct)}% ({so.sales_order.tolerance_source})</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-xs"><thead><tr><th className="text-left">Matrix</th><th className="text-right">Ordered</th><th className="text-right">Shipped</th><th className="text-right">Remaining order</th><th className="text-right">Ceiling</th></tr></thead><tbody>{so.matrix.map(line=><tr key={line.line_id}><td>{line.style} · {line.color} · {line.size}</td><td className="text-right">{fmt(line.ordered_qty)}</td><td className="text-right">{fmt(line.shipped_qty)}</td><td className="text-right">{fmt(line.remaining_to_order_qty)}</td><td className="text-right">{fmt(line.commercial_ceiling_qty)}</td></tr>)}</tbody></table></div><div className="grid gap-2 md:grid-cols-3"><p className="rounded bg-white p-2 text-xs"><b>Delivery schedules:</b> {so.delivery_schedules.rows.length} · scheduled {fmt(so.delivery_schedules.scheduled_qty)}<br/><span className="text-slate-500">Shipment link/remaining: NOT DEFINED</span></p><p className="rounded bg-white p-2 text-xs"><b>Packing Lists:</b> {so.packing_lists.length}</p><p className="rounded bg-white p-2 text-xs"><b>Shipments:</b> {so.shipments.length}<br/><span className="text-slate-500">{so.partial_shipment.status}: {so.partial_shipment.undefined}</span></p></div></div>}
    {shipment&&<div className="space-y-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm"><div className="flex justify-between"><b className="font-mono">{shipment.shipment.doc_no}</b><StatusBadge status={shipment.shipment.status}/></div><p>Qty {fmt(shipment.shipment.qty)} · Packing {shipment.packing_source.doc_no} · ITS {shipment.its_shipment.doc_no??shipment.its_shipment.status}</p><p className="text-xs"><b>Forward:</b> {shipment.lineage.forward}</p><p className="text-xs"><b>Reverse:</b> {shipment.lineage.reverse}</p><p className="text-xs text-slate-600">Delivery Schedule link, Commercial Invoice, Export Documents, Shipment valuation, dan COGS tetap NOT DEFINED. Finance AR Invoice bukan Commercial Invoice PF-09.</p></div>}
  </section>;
}
