<?php

namespace Modules\Reporting\Services;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Modules\Finance\Services\BepService;
use RuntimeException;

class ReportService
{
    public function __construct(private BepService $bep){}
    public function available():array{return['order_status','wip_summary','production_efficiency','qc_summary','stock_aging','consumption_variance','otd','bep_position'];}
    public function permissionFor(string $report):string{return match($report){'order_status','otd'=>'reporting.sales.view','wip_summary','production_efficiency','consumption_variance'=>'reporting.ppic.view','qc_summary'=>'reporting.quality.view','stock_aging'=>'reporting.inventory.view','bep_position'=>'reporting.finance.view',default=>throw new RuntimeException("Report [{$report}] tidak dikenal.")};}
    public function run(int $companyId,string $report,array $params=[]):array
    {
        $limit=max(1,min((int)($params['limit']??1000),5000));
        return match($report){'order_status'=>$this->orderStatus($companyId,$limit),'wip_summary'=>$this->wipSummary($companyId,$limit),'production_efficiency'=>$this->productionEfficiency($companyId,$params,$limit),'qc_summary'=>$this->qcSummary($companyId,$limit),'stock_aging'=>$this->stockAging($companyId,$limit),'consumption_variance'=>$this->consumptionVariance($companyId,$limit),'otd'=>$this->otd($companyId,$limit),'bep_position'=>$this->bepPosition($companyId,$params,$limit),default=>throw new RuntimeException("Report [{$report}] tidak dikenal.")};
    }
    private function orderStatus(int $c,int $limit):array{$rows=DB::table('sales_orders')->where('sales_orders.company_id',$c)->whereNull('sales_orders.deleted_at')->leftJoin('sales_order_lines','sales_order_lines.sales_order_id','=','sales_orders.id')->leftJoin('customers','customers.id','=','sales_orders.customer_id')->selectRaw('sales_orders.doc_no,customers.name customer,sales_orders.status,sales_orders.order_date,sales_orders.ex_factory_date,COALESCE(SUM(sales_order_lines.qty),0) total_qty,COALESCE(SUM(sales_order_lines.qty*sales_order_lines.price),0) total_value')->groupBy('sales_orders.id','sales_orders.doc_no','customers.name','sales_orders.status','sales_orders.order_date','sales_orders.ex_factory_date')->orderByDesc('sales_orders.id')->limit($limit)->get()->all();return['columns'=>['doc_no','customer','status','order_date','ex_factory_date','total_qty','total_value'],'rows'=>$rows];}
    private function wipSummary(int $c,int $limit):array{$rows=DB::table('bundles')->where('bundles.company_id',$c)->whereIn('bundles.status',['ACTIVE','REWORK'])->join('production_orders','production_orders.id','=','bundles.production_order_id')->join('styles','styles.id','=','production_orders.style_id')->selectRaw('production_orders.doc_no mo,styles.style_no,bundles.current_stage,bundles.status,COUNT(*) bundles,SUM(bundles.qty) pcs')->groupBy('production_orders.doc_no','styles.style_no','bundles.current_stage','bundles.status')->orderBy('production_orders.doc_no')->limit($limit)->get()->all();return['columns'=>['mo','style_no','current_stage','status','bundles','pcs'],'rows'=>$rows];}
    private function productionEfficiency(int $c,array $params,int $limit):array{$date=$this->date($params['date']??now()->toDateString());$rows=DB::table('production_scans')->where('production_scans.company_id',$c)->where('production_scans.stage','SEWING')->where('production_scans.direction','OUT')->whereDate('production_scans.scanned_at',$date)->join('bundles','bundles.id','=','production_scans.bundle_id')->join('production_orders','production_orders.id','=','production_scans.production_order_id')->join('routing_versions','routing_versions.id','=','production_orders.routing_version_id')->join('routing_operations as ro','ro.routing_version_id','=','routing_versions.id')->whereColumn('ro.operation_id','production_scans.operation_id')->whereNotExists(fn($q)=>$q->selectRaw('1')->from('routing_operations as later')->whereColumn('later.routing_version_id','ro.routing_version_id')->whereColumn('later.seq','>','ro.seq'))->join('lines','lines.id','=','production_scans.line_id')->selectRaw('lines.code line,SUM(bundles.qty) pcs_output,SUM(bundles.qty*routing_versions.total_sam) sam_earned,MAX(lines.capacity_std) capacity_std')->groupBy('lines.code')->orderBy('lines.code')->limit($limit)->get()->all();return['columns'=>['line','pcs_output','sam_earned','capacity_std'],'rows'=>$rows];}
    private function qcSummary(int $c,int $limit):array{$verdicts=DB::table('qc_inspections')->where('company_id',$c)->selectRaw('stage,verdict,COUNT(*) total')->groupBy('stage','verdict')->get()->all();$rows=DB::table('qc_inspection_lines')->join('qc_inspections','qc_inspections.id','=','qc_inspection_lines.qc_inspection_id')->join('defect_library','defect_library.id','=','qc_inspection_lines.defect_id')->where('qc_inspections.company_id',$c)->selectRaw('defect_library.name,defect_library.severity,SUM(qc_inspection_lines.qty) occurrences')->groupBy('defect_library.name','defect_library.severity')->orderByDesc('occurrences')->limit(min($limit,100))->get()->all();return['columns'=>['name','severity','occurrences'],'rows'=>$rows,'verdict_summary'=>$verdicts];}
    private function stockAging(int $c,int $limit):array{$rows=DB::table('stock_balances')->where('stock_balances.company_id',$c)->where('stock_balances.on_hand','>',0)->whereNotNull('stock_balances.material_id')->join('materials','materials.id','=','stock_balances.material_id')->join('warehouses','warehouses.id','=','stock_balances.warehouse_id')->selectRaw('materials.code,materials.name,warehouses.code warehouse,stock_balances.on_hand,stock_balances.reserved,stock_balances.quality_hold,stock_balances.avg_cost,(stock_balances.on_hand*COALESCE(stock_balances.avg_cost,0)) stock_value,DATEDIFF(CURDATE(),stock_balances.created_at) age_days')->orderByDesc('stock_value')->limit($limit)->get()->all();return['columns'=>['code','name','warehouse','on_hand','reserved','quality_hold','avg_cost','stock_value','age_days'],'rows'=>$rows];}
    private function consumptionVariance(int $c,int $limit):array{$rows=DB::table('mo_material_allocations as a')->join('production_orders as mo','mo.id','=','a.production_order_id')->join('styles','styles.id','=','mo.style_id')->join('materials','materials.id','=','a.material_id')->join('bom_lines as bl',function($j){$j->on('bl.bom_version_id','=','mo.bom_version_id')->on('bl.material_id','=','a.material_id');})->where('mo.company_id',$c)->whereNotNull('a.actual_consumption_per_pcs')->where('bl.qty_per_pcs','>',0)->selectRaw('mo.doc_no mo,styles.style_no,materials.code material,bl.qty_per_pcs,bl.wastage_pct,bl.shrinkage_pct,a.actual_consumption_per_pcs consumption_actual,ROUND((a.actual_consumption_per_pcs-bl.qty_per_pcs)/bl.qty_per_pcs*100,2) variance_pct')->orderByDesc('mo.id')->limit($limit)->get()->all();return['columns'=>['mo','style_no','material','qty_per_pcs','wastage_pct','shrinkage_pct','consumption_actual','variance_pct'],'rows'=>$rows];}
    private function otd(int $c,int $limit):array{$rows=DB::table('shipments')->where('shipments.company_id',$c)->where('shipments.status','SHIPPED')->join('sales_orders','sales_orders.id','=','shipments.sales_order_id')->whereNotNull('sales_orders.ex_factory_date')->selectRaw('shipments.doc_no,sales_orders.doc_no so,sales_orders.ex_factory_date,shipments.ship_date,DATEDIFF(shipments.ship_date,sales_orders.ex_factory_date) days_late')->orderByDesc('shipments.ship_date')->limit($limit)->get()->all();return['columns'=>['doc_no','so','ex_factory_date','ship_date','days_late'],'rows'=>$rows];}
    private function bepPosition(int $c,array $params,int $limit):array{$fixed=(float)($params['fixed_cost_share']??0);if($fixed<0)throw new RuntimeException('Fixed cost share tidak boleh negatif.');$latest=DB::table('cost_sheets')->selectRaw('MAX(id) id')->where('company_id',$c)->where('status','APPROVED')->groupBy('style_id');$styles=DB::table('cost_sheets')->joinSub($latest,'latest',fn($j)=>$j->on('latest.id','=','cost_sheets.id'))->join('styles','styles.id','=','cost_sheets.style_id')->where('cost_sheets.fob_price','>',0)->select('styles.id','styles.style_no')->limit($limit)->get();$rows=[];foreach($styles as $style){$shipped=(float)DB::table('shipment_lines')->join('shipments','shipments.id','=','shipment_lines.shipment_id')->where('shipments.company_id',$c)->where('shipments.status','SHIPPED')->where('shipment_lines.style_id',$style->id)->sum('shipment_lines.qty_shipped');$bep=$fixed>0?$this->bep->forStyle($c,$style->id,$fixed):null;$rows[]=['style_no'=>$style->style_no,'qty_shipped'=>$shipped,'bep_qty'=>$bep['bep_qty']??null,'position'=>$bep?($shipped>=$bep['bep_qty']?'ABOVE_BEP':'BELOW_BEP'):'NO_FIXED_COST_INPUT'];}return['columns'=>['style_no','qty_shipped','bep_qty','position'],'rows'=>$rows];}
    public function toCsv(array $report):string{$out=fopen('php://temp','r+');fputcsv($out,$report['columns'],';', '"','\\');foreach($report['rows'] as $row){fputcsv($out,array_map(function($column)use($row){$value=is_array($row)?($row[$column]??null):($row->{$column}??null);if(is_string($value)&&preg_match('/^[=+\-@]/',$value))$value="'".$value;return $value;},$report['columns']),';','"','\\');}rewind($out);$csv="\xEF\xBB\xBF".stream_get_contents($out);fclose($out);return $csv;}
    private function date(string $value):string{try{return Carbon::createFromFormat('Y-m-d',$value)->format('Y-m-d');}catch(\Throwable){throw new RuntimeException('Date report wajib format YYYY-MM-DD.');}}
}
